////////////////////////////////////////////////////////////////////////////////
//
// Filename:	rtl/video/vid_dicap.v
// {{{
// Project:	VideoZip, a ZipCPU SoC supporting video functionality
//
// Purpose:	Given a byte stream generated by HDMI data islands, this module
//		packs such a stream into 32b words for (eventual) collection
//	and analysis via a WB Scope.
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2015-2024, Gisselquist Technology, LLC
// {{{
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
// }}}
// License:	GPL, v3, as defined and found on www.gnu.org,
// {{{
//		http://www.gnu.org/licenses/gpl.html
//
////////////////////////////////////////////////////////////////////////////////
//
`default_nettype	none
`define	WISHBONE
// }}}
module	vid_dicap (
		input	wire		i_clk, i_reset,
		//
		input	wire		S_VALID,
		output	wire		S_READY,
		input	wire	[7:0]	S_DATA,
		input	wire		S_LAST,
		//
		output	wire		o_vld,
		output	wire	[31:0]	o_debug,
		output	wire		o_last
	);

	reg		sof, gated;

	wire		gbx_valid, gbx_ready, gbx_last, gbx_iready;
	wire	[1:0]	ign_gbx_bytes;
	wire	[31:0]	gbx_data;

	always @(posedge i_clk)
	if (i_reset)
		sof <= 1'b1;
	else if (S_VALID && S_READY)
		sof <= S_LAST;

	always @(posedge i_clk)
	if (i_reset)
		gated <= 1'b0;
	else if (S_VALID && S_READY && sof)
		gated <= 1'b0;	// == S_DATA == PKT_OF_INTEREST

	// I suppose we might also pack these into 31 bit words using a
	// different gearbox.
	//	31 bytes would fit into 8x 31bit words, but then we'd lose
	//	the boundaries.
	zipdma_rxgears #(
		.BUS_WIDTH(32)
	) gearbox (
		.i_clk(i_clk), .i_reset(i_reset), .i_soft_reset(1'b0),
		.S_VALID(S_VALID && !gated), .S_READY(gbx_iready),
		.S_DATA({ S_DATA, 24'h0 }), .S_BYTES(2'b01), .S_LAST(S_LAST),
		.M_VALID(gbx_valid), .M_READY(gbx_ready),
		.M_DATA(gbx_data), .M_BYTES(ign_gbx_bytes),
		.M_LAST(gbx_last)
	);

	assign	gbx_ready = 1'b1;
	assign	o_vld   = gbx_valid;
	assign	o_debug = gbx_data;
	assign	o_last  = gbx_last;
	assign	S_READY = gbx_iready || gated;

	// Verilator lint_off UNUSED
	wire	unused;
	assign	unused = &{ 1'b0, ign_gbx_bytes };
	// Verilator lint_on  UNUSED
endmodule
