////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./iscachable.v
// {{{
// Project:	VideoZip, a ZipCPU SoC supporting video functionality
//
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga -d -o . allclocks.txt genclk.txt netclockctr.txt global.txt icape.txt crossbus.txt wbuarbiter.txt version.txt buserr.txt pwrcount.txt rtccount.txt spio.txt gpio.txt vadj33.txt rtclight.txt rtcdate.txt exconsole.txt wbuuart.txt bkram.txt flash.txt flashcfg.txt sdram.txt zipmaster.txt mdio.txt meganet.txt protocols.txt nexbus.txt sdio.txt hdmi.txt edid.txt wboledbw.txt cpuscope.txt vidscope.txt sdioscope.txt edidscope.txt mem_bkram_only.txt mem_flash_bkram.txt xdc.txt clkcounter.txt i2ccpu.txt wbrotary.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2015-2024, Gisselquist Technology, LLC
// {{{
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
// }}}
// License:	GPL, v3, as defined and found on www.gnu.org,
// {{{
//		http://www.gnu.org/licenses/gpl.html
//
////////////////////////////////////////////////////////////////////////////////
//
// }}}
`default_nettype none
//
module iscachable(
		// {{{
		input	wire	[30-1:0]	i_addr,
		output	reg			o_cachable
		// }}}
	);

	always @(*)
	begin
		o_cachable = 1'b0;
		// Bus master: wbwide
		// Bus master: wbflash
		// flash
		if ((i_addr[29:0] & 30'h39000000) == 30'h01000000)
			o_cachable = 1'b1;
		// Bus master: wb32
		// Bus master: wb32_dio
		// Bus master: wb32_sio
		// bkram
		if ((i_addr[29:0] & 30'h38000000) == 30'h10000000)
			o_cachable = 1'b1;
		// sdram
		if ((i_addr[29:0] & 30'h20000000) == 30'h20000000)
			o_cachable = 1'b1;
	end

endmodule
