`timescale	1ps / 1ps
////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./main.v
//
// Project:	VideoZip, a ZipCPU SoC supporting video functionality
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga autofpga -d -o . allclocks.txt genclk.txt netclockctr.txt global.txt icape.txt version.txt buserr.txt pic.txt pwrcount.txt xpander.txt spio.txt gpio.txt rtcgps.txt rtcdate.txt wbuconsole.txt bkram.txt flash.txt sdram.txt zipmaster.txt mdio.txt enet.txt gps.txt sdspi.txt cpuscope.txt mem_bkram_only.txt mem_flash_bkram.txt xdc.txt clkcounter.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2017-2019, Gisselquist Technology, LLC
//
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of  the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
//
// License:	GPL, v3, as defined and found on www.gnu.org,
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
//
`default_nettype	none
//
//
// Here is a list of defines which may be used, post auto-design
// (not post-build), to turn particular peripherals (and bus masters)
// on and off.  In particular, to turn off support for a particular
// design component, just comment out its respective `define below.
//
// These lines are taken from the respective @ACCESS tags for each of our
// components.  If a component doesn't have an @ACCESS tag, it will not
// be listed here.
//
// First, the independent access fields for any bus masters
`define	WBUBUS_MASTER
`define	ALLCLOCKS_PRESENT
// And then for the independent peripherals
`define	GPSTRK_ACCESS
`define	ETHERNET_ACCESS
`define	INCLUDE_ZIPCPU
`define	GPIO_ACCESS
`define	CFG_ACCESS
`define	FLASH_ACCESS
`define	GPSUART_ACCESS
`define	BUSPIC_ACCESS
`define	ARBITRARY_CLOCK_GENERATOR_ACCESS
`define	RTC_ACCESS
`define	BKRAM_ACCESS
`define	SDSPI_ACCESS
`define	SPIO_ACCESS
`define	PWRCOUNT_ACCESS
`define	BUSCONSOLE_ACCESS
`define	NETCTRL_ACCESS
//
//
// The list of those things that have @DEPENDS tags
//
//
//
// Dependencies
// Any core with both an @ACCESS and a @DEPENDS tag will show up here.
// The @DEPENDS tag will turn into a series of ifdef's, with the @ACCESS
// being defined only if all of the ifdef's are true//
`ifdef	RTC_ACCESS
`define	RTCDATE_ACCESS
`endif	// RTC_ACCESS
`ifdef	FLASH_ACCESS
`define	FLASHCFG_ACCESS
`endif	// FLASH_ACCESS
`ifdef	ALLCLOCKS_PRESENT
`define	SDRAM_ACCESS
`endif	// ALLCLOCKS_PRESENT
`ifdef	INCLUDE_ZIPCPU
`define	ZIPSCOPE_SCOPE
`endif	// INCLUDE_ZIPCPU
`ifdef	ETHERNET_ACCESS
`define	NETTXCLK_ACCESS
`endif	// ETHERNET_ACCESS
`ifdef	ETHERNET_ACCESS
`ifdef	GPSTRK_ACCESS
`define	NETCLOCKCTR_ACCESS
`endif	// GPSTRK_ACCESS
`endif	// ETHERNET_ACCESS
//
// End of dependency list
//
//
//
//
// Finally, we define our main module itself.  We start with the list of
// I/O ports, or wires, passed into (or out of) the main function.
//
// These fields are copied verbatim from the respective I/O port lists,
// from the fields given by @MAIN.PORTLIST
//
module	main(i_clk, i_reset,
		// The GPS 1PPS signal port
		i_gps_pps,
		// Ethernet control (packets) lines
		o_net_reset_n,
		// eth_int_b	// Interrupt, leave floating
		// eth_pme_b	// Power management event, leave floating
		i_net_rx_clk, i_net_rx_dv, i_net_rx_err, i_net_rxd,
		o_net_tx_clk, o_net_tx_ctl, o_net_txd,
		i_cpu_reset,
		// GPIO ports
		i_gpio, o_gpio,
		// UART/host to wishbone interface
		i_wbu_uart_rx, o_wbu_uart_tx,
		// SDRAM ports
		o_sdram_cyc, o_sdram_stb, o_sdram_we,
				o_sdram_addr, o_sdram_data, o_sdram_sel,
			i_sdram_stall, i_sdram_ack, i_sdram_data,
			i_sdram_err
			, i_sdram_dbg,
		// The Universal QSPI Flash
		o_qspi_cs_n, o_qspi_sck, o_qspi_dat, i_qspi_dat, o_qspi_mod,
		// The GPS-UART
		i_gpsu_rx, o_gpsu_tx,
		// Clock generator ports
		i_genclk_clk,
		i_genclk_pll_locked,
		o_genclk_word,
		o_genclk_ce,
		// Extra clocks
		i_clk_200mhz, i_clk_125mhz,
		// The SD-Card wires
		o_sd_sck, o_sd_cmd, o_sd_data, i_sd_cmd, i_sd_data, i_sd_detect,
		// SPIO interface
		i_sw, i_btnc, i_btnd, i_btnl, i_btnr, i_btnu, o_led,
		// The ethernet MDIO wires
		o_mdclk, o_mdio, o_mdwe, i_mdio);
//
// Any parameter definitions
//
// These are drawn from anything with a MAIN.PARAM definition.
// As they aren't connected to the toplevel at all, it would
// be best to use localparam over parameter, but here we don't
// check
	localparam [31:0] GPSCLOCK_DEFAULT_STEP = 32'haabcc771;
	//
	//
	// Variables/definitions needed by the ZipCPU BUS master
	//
	//
	// A 32-bit address indicating where the ZipCPU should start running
	// from
`ifdef	BKROM_ACCESS
	localparam	RESET_ADDRESS = @$(/bkrom.BASE);
`else
`ifdef	FLASH_ACCESS
	localparam	RESET_ADDRESS = 375390208;
`else
	localparam	RESET_ADDRESS = 335544320;
`endif	// FLASH_ACCESS
`endif	// BKROM_ACCESS
	//
	// The number of valid bits on the bus
	localparam	ZIP_ADDRESS_WIDTH = 28; // Zip-CPU address width
	//
	// Number of ZipCPU interrupts
	localparam	ZIP_INTS = 16;
	//
	// ZIP_START_HALTED
	//
	// A boolean, indicating whether or not the ZipCPU be halted on startup?
`ifdef	BKROM_ACCESS
	localparam	ZIP_START_HALTED=1'b0;
`else
	localparam	ZIP_START_HALTED=1'b1;
`endif
	//
	// WBUBUS parameters
	//
	// Baudrate :   2000000
	// Clock    : 100000000
	localparam [23:0] BUSUART = 24'h32;	//   2000000 baud
	localparam	DBGBUSBITS = $clog2(BUSUART);
	//
	// Maximum command is 6 bytes, where each byte takes 10 baud clocks
	// and each baud clock requires DBGBUSBITS to represent.  Here,
	// we'll add one more for good measure.
	localparam	DBGBUSWATCHDOG_RAW = DBGBUSBITS + 9;
	localparam	DBGBUSWATCHDOG = (DBGBUSWATCHDOG_RAW > 19)
				? DBGBUSWATCHDOG_RAW : 19;
	localparam	ICAPE_LGDIV=3;
//
// The next step is to declare all of the various ports that were just
// listed above.  
//
// The following declarations are taken from the values of the various
// @MAIN.IODECL keys.
//
	input	wire		i_clk;
	// verilator lint_off UNUSED
	input	wire		i_reset;
	// verilator lint_on UNUSED
	//The GPS Clock
	input	wire		i_gps_pps;
	// Ethernet (RGMII) control
	output	wire		o_net_reset_n;
	input	wire		i_net_rx_clk, i_net_rx_dv, i_net_rx_err;
	input	wire	[7:0]	i_net_rxd;
	output	wire	[1:0]	o_net_tx_clk;
	output	wire		o_net_tx_ctl;
	output	wire	[7:0]	o_net_txd;
	input	wire		i_cpu_reset;
	localparam	NGPI = 16, NGPO=16;
	// GPIO ports
	input		[(NGPI-1):0]	i_gpio;
	output	wire	[(NGPO-1):0]	o_gpio;
	input	wire		i_wbu_uart_rx;
	output	wire		o_wbu_uart_tx;
	// SDRAM I/O declarations
	output	wire			o_sdram_cyc,
					o_sdram_stb, o_sdram_we;
	output	wire	[25-1:0]	o_sdram_addr;
	output	wire	[(128-1):0]	o_sdram_data;
	output	wire	[(128/8)-1:0]	o_sdram_sel;
	//
	input	wire			i_sdram_ack;
	input	wire			i_sdram_stall;
	input	wire	[(128-1):0]	i_sdram_data;
	// Verilator lint_off UNUSED
	input	wire			i_sdram_err;
	input	wire	[31:0]		i_sdram_dbg;
	// Verilator lint_on  UNUSED
	// The Universal QSPI flash
	output	wire		o_qspi_cs_n, o_qspi_sck;
	output	wire	[3:0]	o_qspi_dat;
	input	wire	[3:0]	i_qspi_dat;
	output	wire	[1:0]	o_qspi_mod;
	input	wire		i_gpsu_rx;
	output	wire		o_gpsu_tx;
	input	wire		i_genclk_clk;
	input	wire		i_genclk_pll_locked;
	output	wire	[7:0]	o_genclk_word;
	output	wire		o_genclk_ce;
	// Extra clocks
	// Verilator lint_off UNUSED
	input	wire		i_clk_200mhz, i_clk_125mhz;
	// Verilator lint_on  UNUSED
	// SD-Card declarations
	output	wire		o_sd_sck, o_sd_cmd;
	output	wire	[3:0]	o_sd_data;
	// verilator lint_off UNUSED
	input	wire		i_sd_cmd;
	input	wire	[3:0]	i_sd_data;
	// verilator lint_on  UNUSED
	input	wire		i_sd_detect;
	// SPIO interface
	input	wire	[8-1:0]	i_sw;
	input	wire		i_btnc, i_btnd, i_btnl, i_btnr, i_btnu;
	output	wire	[8-1:0]	o_led;
	// Ethernet control (MDIO)
	output	wire		o_mdclk, o_mdio, o_mdwe;
	input	wire		i_mdio;
	// Make Verilator happy ... defining bus wires for lots of components
	// often ends up with unused wires lying around.  We'll turn off
	// Ver1lator's lint warning here that checks for unused wires.
	// verilator lint_off UNUSED



	//
	// Declaring interrupt lines
	//
	// These declarations come from the various components values
	// given under the @INT.<interrupt name>.WIRE key.
	//
	wire	ck_pps;	// gck.INT.PPS.WIRE
	wire	nettx_int;	// netp.INT.NETTX.WIRE
	wire	netrx_int;	// netp.INT.NETRX.WIRE
	wire	zip_cpu_int;	// zip.INT.ZIP.WIRE
	wire	gpio_int;	// gpio.INT.GPIO.WIRE
	wire	gpsutx_int;	// gpsu.INT.GPSTX.WIRE
	wire	gpsutxf_int;	// gpsu.INT.GPSTXF.WIRE
	wire	gpsurx_int;	// gpsu.INT.GPSRX.WIRE
	wire	gpsurxf_int;	// gpsu.INT.GPSRXF.WIRE
	wire	w_bus_int;	// buspic.INT.BUS.WIRE
	wire	rtc_int;	// rtc.INT.RTC.WIRE
	wire	sdcard_int;	// sdcard.INT.SDCARD.WIRE
	wire	spio_int;	// spio.INT.SPIO.WIRE
	wire	uarttxf_int;	// uart.INT.UARTTXF.WIRE
	wire	uartrxf_int;	// uart.INT.UARTRXF.WIRE
	wire	uarttx_int;	// uart.INT.UARTTX.WIRE
	wire	uartrx_int;	// uart.INT.UARTRX.WIRE


	//
	// Component declarations
	//
	// These declarations come from the @MAIN.DEFNS keys found in the
	// various components comprising the design.
	//
// Looking for string: MAIN.DEFNS
	reg	r_sysclk_ack;
	wire	gps_pps, gps_led, gps_locked, gps_tracking;
	wire	[63:0]	gps_now, gps_err, gps_step;
	wire	[1:0]	gps_dbg_tick;
	wire	tb_pps;
	//
	wire		netp_debug_clk;
	wire	[31:0]	netp_debug;
	// ZipSystem/ZipCPU connection definitions
	// All we define here is a set of scope wires
	wire	[31:0]	zip_debug;
	wire		zip_trigger;
	wire	[ZIP_INTS-1:0] zip_int_vector;
`include "builddate.v"
	wire	sd_reset;
	// Remove this scope tag via inheritance when/if you connect the
	// scope interrupt
	//
	// Virilator lint_off UNUSED
	wire	zipscope_int;
	// Virilator lint_on  UNUSED
	//
	//
	// UART interface
	//
	//
	wire	[7:0]	wbu_rx_data, wbu_tx_data;
	wire		wbu_rx_stb;
	wire		wbu_tx_stb, wbu_tx_busy;

	wire	w_ck_uart, w_uart_tx;
	// Definitions for the WB-UART converter.  We really only need one
	// (more) non-bus wire--one to use to select if we are interacting
	// with the ZipCPU or not.
	wire	[0:0]	wbubus_dbg;
`ifndef	INCLUDE_ZIPCPU
	//
	// The bus-console depends upon the zip_dbg wires.  If there is no
	// ZipCPU defining them, we'll need to define them here anyway.
	//
	wire		zip_dbg_stall, zip_dbg_ack;
	wire	[31:0]	zip_dbg_data;
`endif
	reg	[29-1:0]	r_buserr_addr;
// BUILDTIME doesnt need to include builddate.v a second time
// `include "builddate.v"
	// Definitions for the flash debug port
	wire		flash_dbg_trigger;
	wire	[31:0]	flash_debug;
	wire	w_gpsu_cts_n, w_gpsu_rts_n;
	assign	w_gpsu_cts_n=1'b1;
	reg	r_genclk_test_ack;
`ifndef	GPSTRK_ACCESS
	reg	[31:0]	r_subseconds_data;
`endif
	reg	[30:0]	r_genclk_data;
	wire		w_genclk_stb;
	reg		r_genclk_ack;
	reg	r_nettxctr_ack;
	wire	i_net_tx_clk;
	// Definitions in support of the GPS driven RTC
	// This clock step is designed to match 100000000 Hz
	localparam	[31:0]	RTC_CLKSTEP = 32'h002af31d;
	wire	rtc_ppd;
	reg	r_rtc_ack;
`ifdef	GPSTRK_ACCESS
	wire	rtc_pps;
`endif
	reg	r_netclockctr_ack;
	wire[31:0]	sdspi_debug;
	wire	[5-1:0]	w_btn;
	wire	[8-1:0]	w_led;
	reg	[31:0]	r_pwrcount_data;
	// Console definitions
	wire		w_console_rx_stb, w_console_tx_stb, w_console_busy;
	wire	[6:0]	w_console_rx_data, w_console_tx_data;
	wire	[31:0]	uart_debug;


	//
	// Declaring interrupt vector wires
	//
	// These declarations come from the various components having
	// PIC and PIC.MAX keys.
	//
	wire	[14:0]	bus_int_vector;
	wire	[14:0]	alt_int_vector;
	wire	[14:0]	sys_int_vector;
	//
	//
	// Define bus wires
	//
	//

	// Bus wb
	// Wishbone definitions for bus wb, component zip
	// Verilator lint_off UNUSED
	wire		wb_zip_cyc, wb_zip_stb, wb_zip_we;
	wire	[27:0]	wb_zip_addr;
	wire	[31:0]	wb_zip_data;
	wire	[3:0]	wb_zip_sel;
	wire		wb_zip_stall, wb_zip_ack, wb_zip_err;
	wire	[31:0]	wb_zip_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component wbu_arbiter
	// Verilator lint_off UNUSED
	wire		wb_wbu_arbiter_cyc, wb_wbu_arbiter_stb, wb_wbu_arbiter_we;
	wire	[27:0]	wb_wbu_arbiter_addr;
	wire	[31:0]	wb_wbu_arbiter_data;
	wire	[3:0]	wb_wbu_arbiter_sel;
	wire		wb_wbu_arbiter_stall, wb_wbu_arbiter_ack, wb_wbu_arbiter_err;
	wire	[31:0]	wb_wbu_arbiter_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component buildtime
	// Verilator lint_off UNUSED
	wire		wb_buildtime_cyc, wb_buildtime_stb, wb_buildtime_we;
	wire	[27:0]	wb_buildtime_addr;
	wire	[31:0]	wb_buildtime_data;
	wire	[3:0]	wb_buildtime_sel;
	wire		wb_buildtime_stall, wb_buildtime_ack, wb_buildtime_err;
	wire	[31:0]	wb_buildtime_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component buserr
	// Verilator lint_off UNUSED
	wire		wb_buserr_cyc, wb_buserr_stb, wb_buserr_we;
	wire	[27:0]	wb_buserr_addr;
	wire	[31:0]	wb_buserr_data;
	wire	[3:0]	wb_buserr_sel;
	wire		wb_buserr_stall, wb_buserr_ack, wb_buserr_err;
	wire	[31:0]	wb_buserr_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component buspic
	// Verilator lint_off UNUSED
	wire		wb_buspic_cyc, wb_buspic_stb, wb_buspic_we;
	wire	[27:0]	wb_buspic_addr;
	wire	[31:0]	wb_buspic_data;
	wire	[3:0]	wb_buspic_sel;
	wire		wb_buspic_stall, wb_buspic_ack, wb_buspic_err;
	wire	[31:0]	wb_buspic_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component genclk
	// Verilator lint_off UNUSED
	wire		wb_genclk_cyc, wb_genclk_stb, wb_genclk_we;
	wire	[27:0]	wb_genclk_addr;
	wire	[31:0]	wb_genclk_data;
	wire	[3:0]	wb_genclk_sel;
	wire		wb_genclk_stall, wb_genclk_ack, wb_genclk_err;
	wire	[31:0]	wb_genclk_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component genclk_test
	// Verilator lint_off UNUSED
	wire		wb_genclk_test_cyc, wb_genclk_test_stb, wb_genclk_test_we;
	wire	[27:0]	wb_genclk_test_addr;
	wire	[31:0]	wb_genclk_test_data;
	wire	[3:0]	wb_genclk_test_sel;
	wire		wb_genclk_test_stall, wb_genclk_test_ack, wb_genclk_test_err;
	wire	[31:0]	wb_genclk_test_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component gpio
	// Verilator lint_off UNUSED
	wire		wb_gpio_cyc, wb_gpio_stb, wb_gpio_we;
	wire	[27:0]	wb_gpio_addr;
	wire	[31:0]	wb_gpio_data;
	wire	[3:0]	wb_gpio_sel;
	wire		wb_gpio_stall, wb_gpio_ack, wb_gpio_err;
	wire	[31:0]	wb_gpio_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component netclockctr
	// Verilator lint_off UNUSED
	wire		wb_netclockctr_cyc, wb_netclockctr_stb, wb_netclockctr_we;
	wire	[27:0]	wb_netclockctr_addr;
	wire	[31:0]	wb_netclockctr_data;
	wire	[3:0]	wb_netclockctr_sel;
	wire		wb_netclockctr_stall, wb_netclockctr_ack, wb_netclockctr_err;
	wire	[31:0]	wb_netclockctr_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component nettxctr
	// Verilator lint_off UNUSED
	wire		wb_nettxctr_cyc, wb_nettxctr_stb, wb_nettxctr_we;
	wire	[27:0]	wb_nettxctr_addr;
	wire	[31:0]	wb_nettxctr_data;
	wire	[3:0]	wb_nettxctr_sel;
	wire		wb_nettxctr_stall, wb_nettxctr_ack, wb_nettxctr_err;
	wire	[31:0]	wb_nettxctr_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component pwrcount
	// Verilator lint_off UNUSED
	wire		wb_pwrcount_cyc, wb_pwrcount_stb, wb_pwrcount_we;
	wire	[27:0]	wb_pwrcount_addr;
	wire	[31:0]	wb_pwrcount_data;
	wire	[3:0]	wb_pwrcount_sel;
	wire		wb_pwrcount_stall, wb_pwrcount_ack, wb_pwrcount_err;
	wire	[31:0]	wb_pwrcount_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component rtcdate
	// Verilator lint_off UNUSED
	wire		wb_rtcdate_cyc, wb_rtcdate_stb, wb_rtcdate_we;
	wire	[27:0]	wb_rtcdate_addr;
	wire	[31:0]	wb_rtcdate_data;
	wire	[3:0]	wb_rtcdate_sel;
	wire		wb_rtcdate_stall, wb_rtcdate_ack, wb_rtcdate_err;
	wire	[31:0]	wb_rtcdate_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component spio
	// Verilator lint_off UNUSED
	wire		wb_spio_cyc, wb_spio_stb, wb_spio_we;
	wire	[27:0]	wb_spio_addr;
	wire	[31:0]	wb_spio_data;
	wire	[3:0]	wb_spio_sel;
	wire		wb_spio_stall, wb_spio_ack, wb_spio_err;
	wire	[31:0]	wb_spio_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component subseconds
	// Verilator lint_off UNUSED
	wire		wb_subseconds_cyc, wb_subseconds_stb, wb_subseconds_we;
	wire	[27:0]	wb_subseconds_addr;
	wire	[31:0]	wb_subseconds_data;
	wire	[3:0]	wb_subseconds_sel;
	wire		wb_subseconds_stall, wb_subseconds_ack, wb_subseconds_err;
	wire	[31:0]	wb_subseconds_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component sysclk
	// Verilator lint_off UNUSED
	wire		wb_sysclk_cyc, wb_sysclk_stb, wb_sysclk_we;
	wire	[27:0]	wb_sysclk_addr;
	wire	[31:0]	wb_sysclk_data;
	wire	[3:0]	wb_sysclk_sel;
	wire		wb_sysclk_stall, wb_sysclk_ack, wb_sysclk_err;
	wire	[31:0]	wb_sysclk_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(SIO), component version
	// Verilator lint_off UNUSED
	wire		wb_version_cyc, wb_version_stb, wb_version_we;
	wire	[27:0]	wb_version_addr;
	wire	[31:0]	wb_version_data;
	wire	[3:0]	wb_version_sel;
	wire		wb_version_stall, wb_version_ack, wb_version_err;
	wire	[31:0]	wb_version_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(DIO), component gck
	// Verilator lint_off UNUSED
	wire		wb_gck_cyc, wb_gck_stb, wb_gck_we;
	wire	[27:0]	wb_gck_addr;
	wire	[31:0]	wb_gck_data;
	wire	[3:0]	wb_gck_sel;
	wire		wb_gck_stall, wb_gck_ack, wb_gck_err;
	wire	[31:0]	wb_gck_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(DIO), component rtc
	// Verilator lint_off UNUSED
	wire		wb_rtc_cyc, wb_rtc_stb, wb_rtc_we;
	wire	[27:0]	wb_rtc_addr;
	wire	[31:0]	wb_rtc_data;
	wire	[3:0]	wb_rtc_sel;
	wire		wb_rtc_stall, wb_rtc_ack, wb_rtc_err;
	wire	[31:0]	wb_rtc_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(DIO), component gtb
	// Verilator lint_off UNUSED
	wire		wb_gtb_cyc, wb_gtb_stb, wb_gtb_we;
	wire	[27:0]	wb_gtb_addr;
	wire	[31:0]	wb_gtb_data;
	wire	[3:0]	wb_gtb_sel;
	wire		wb_gtb_stall, wb_gtb_ack, wb_gtb_err;
	wire	[31:0]	wb_gtb_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(DIO), component netp
	// Verilator lint_off UNUSED
	wire		wb_netp_cyc, wb_netp_stb, wb_netp_we;
	wire	[27:0]	wb_netp_addr;
	wire	[31:0]	wb_netp_data;
	wire	[3:0]	wb_netp_sel;
	wire		wb_netp_stall, wb_netp_ack, wb_netp_err;
	wire	[31:0]	wb_netp_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb(DIO), component wb_sio
	// Verilator lint_off UNUSED
	wire		wb_sio_cyc, wb_sio_stb, wb_sio_we;
	wire	[27:0]	wb_sio_addr;
	wire	[31:0]	wb_sio_data;
	wire	[3:0]	wb_sio_sel;
	wire		wb_sio_stall, wb_sio_ack, wb_sio_err;
	wire	[31:0]	wb_sio_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component flashcfg
	// Verilator lint_off UNUSED
	wire		wb_flashcfg_cyc, wb_flashcfg_stb, wb_flashcfg_we;
	wire	[27:0]	wb_flashcfg_addr;
	wire	[31:0]	wb_flashcfg_data;
	wire	[3:0]	wb_flashcfg_sel;
	wire		wb_flashcfg_stall, wb_flashcfg_ack, wb_flashcfg_err;
	wire	[31:0]	wb_flashcfg_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component zipscope
	// Verilator lint_off UNUSED
	wire		wb_zipscope_cyc, wb_zipscope_stb, wb_zipscope_we;
	wire	[27:0]	wb_zipscope_addr;
	wire	[31:0]	wb_zipscope_data;
	wire	[3:0]	wb_zipscope_sel;
	wire		wb_zipscope_stall, wb_zipscope_ack, wb_zipscope_err;
	wire	[31:0]	wb_zipscope_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component gpsu
	// Verilator lint_off UNUSED
	wire		wb_gpsu_cyc, wb_gpsu_stb, wb_gpsu_we;
	wire	[27:0]	wb_gpsu_addr;
	wire	[31:0]	wb_gpsu_data;
	wire	[3:0]	wb_gpsu_sel;
	wire		wb_gpsu_stall, wb_gpsu_ack, wb_gpsu_err;
	wire	[31:0]	wb_gpsu_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component sdcard
	// Verilator lint_off UNUSED
	wire		wb_sdcard_cyc, wb_sdcard_stb, wb_sdcard_we;
	wire	[27:0]	wb_sdcard_addr;
	wire	[31:0]	wb_sdcard_data;
	wire	[3:0]	wb_sdcard_sel;
	wire		wb_sdcard_stall, wb_sdcard_ack, wb_sdcard_err;
	wire	[31:0]	wb_sdcard_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component uart
	// Verilator lint_off UNUSED
	wire		wb_uart_cyc, wb_uart_stb, wb_uart_we;
	wire	[27:0]	wb_uart_addr;
	wire	[31:0]	wb_uart_data;
	wire	[3:0]	wb_uart_sel;
	wire		wb_uart_stall, wb_uart_ack, wb_uart_err;
	wire	[31:0]	wb_uart_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component cfg
	// Verilator lint_off UNUSED
	wire		wb_cfg_cyc, wb_cfg_stb, wb_cfg_we;
	wire	[27:0]	wb_cfg_addr;
	wire	[31:0]	wb_cfg_data;
	wire	[3:0]	wb_cfg_sel;
	wire		wb_cfg_stall, wb_cfg_ack, wb_cfg_err;
	wire	[31:0]	wb_cfg_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component mdio
	// Verilator lint_off UNUSED
	wire		wb_mdio_cyc, wb_mdio_stb, wb_mdio_we;
	wire	[27:0]	wb_mdio_addr;
	wire	[31:0]	wb_mdio_data;
	wire	[3:0]	wb_mdio_sel;
	wire		wb_mdio_stall, wb_mdio_ack, wb_mdio_err;
	wire	[31:0]	wb_mdio_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component wb_dio
	// Verilator lint_off UNUSED
	wire		wb_dio_cyc, wb_dio_stb, wb_dio_we;
	wire	[27:0]	wb_dio_addr;
	wire	[31:0]	wb_dio_data;
	wire	[3:0]	wb_dio_sel;
	wire		wb_dio_stall, wb_dio_ack, wb_dio_err;
	wire	[31:0]	wb_dio_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component netb
	// Verilator lint_off UNUSED
	wire		wb_netb_cyc, wb_netb_stb, wb_netb_we;
	wire	[27:0]	wb_netb_addr;
	wire	[31:0]	wb_netb_data;
	wire	[3:0]	wb_netb_sel;
	wire		wb_netb_stall, wb_netb_ack, wb_netb_err;
	wire	[31:0]	wb_netb_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component bkram
	// Verilator lint_off UNUSED
	wire		wb_bkram_cyc, wb_bkram_stb, wb_bkram_we;
	wire	[27:0]	wb_bkram_addr;
	wire	[31:0]	wb_bkram_data;
	wire	[3:0]	wb_bkram_sel;
	wire		wb_bkram_stall, wb_bkram_ack, wb_bkram_err;
	wire	[31:0]	wb_bkram_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component flash
	// Verilator lint_off UNUSED
	wire		wb_flash_cyc, wb_flash_stb, wb_flash_we;
	wire	[27:0]	wb_flash_addr;
	wire	[31:0]	wb_flash_data;
	wire	[3:0]	wb_flash_sel;
	wire		wb_flash_stall, wb_flash_ack, wb_flash_err;
	wire	[31:0]	wb_flash_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wb, component xpand
	// Verilator lint_off UNUSED
	wire		wb_xpand_cyc, wb_xpand_stb, wb_xpand_we;
	wire	[27:0]	wb_xpand_addr;
	wire	[31:0]	wb_xpand_data;
	wire	[3:0]	wb_xpand_sel;
	wire		wb_xpand_stall, wb_xpand_ack, wb_xpand_err;
	wire	[31:0]	wb_xpand_idata;
	// Verilator lint_on UNUSED
	// Bus wbu
	// Wishbone definitions for bus wbu, component wbu
	// Verilator lint_off UNUSED
	wire		wbu_wbu_cyc, wbu_wbu_stb, wbu_wbu_we;
	wire	[28:0]	wbu_wbu_addr;
	wire	[31:0]	wbu_wbu_data;
	wire	[3:0]	wbu_wbu_sel;
	wire		wbu_wbu_stall, wbu_wbu_ack, wbu_wbu_err;
	wire	[31:0]	wbu_wbu_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbu, component wbu_arbiter
	// Verilator lint_off UNUSED
	wire		wbu_wbu_arbiter_cyc, wbu_wbu_arbiter_stb, wbu_wbu_arbiter_we;
	wire	[28:0]	wbu_wbu_arbiter_addr;
	wire	[31:0]	wbu_wbu_arbiter_data;
	wire	[3:0]	wbu_wbu_arbiter_sel;
	wire		wbu_wbu_arbiter_stall, wbu_wbu_arbiter_ack, wbu_wbu_arbiter_err;
	wire	[31:0]	wbu_wbu_arbiter_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus wbu, component zip
	// Verilator lint_off UNUSED
	wire		wbu_zip_cyc, wbu_zip_stb, wbu_zip_we;
	wire	[28:0]	wbu_zip_addr;
	wire	[31:0]	wbu_zip_data;
	wire	[3:0]	wbu_zip_sel;
	wire		wbu_zip_stall, wbu_zip_ack, wbu_zip_err;
	wire	[31:0]	wbu_zip_idata;
	// Verilator lint_on UNUSED
	// Bus rambus
	// Wishbone definitions for bus rambus, component xpand
	// Verilator lint_off UNUSED
	wire		rambus_xpand_cyc, rambus_xpand_stb, rambus_xpand_we;
	wire	[24:0]	rambus_xpand_addr;
	wire	[127:0]	rambus_xpand_data;
	wire	[15:0]	rambus_xpand_sel;
	wire		rambus_xpand_stall, rambus_xpand_ack, rambus_xpand_err;
	wire	[127:0]	rambus_xpand_idata;
	// Verilator lint_on UNUSED
	// Wishbone definitions for bus rambus, component sdram
	// Verilator lint_off UNUSED
	wire		rambus_sdram_cyc, rambus_sdram_stb, rambus_sdram_we;
	wire	[24:0]	rambus_sdram_addr;
	wire	[127:0]	rambus_sdram_data;
	wire	[15:0]	rambus_sdram_sel;
	wire		rambus_sdram_stall, rambus_sdram_ack, rambus_sdram_err;
	wire	[127:0]	rambus_sdram_idata;
	// Verilator lint_on UNUSED

	//
	// Peripheral address decoding
	//
	//
	// BUS-LOGIC for wb
	//
	//
	// wb Bus logic to handle SINGLE slaves
	//
	reg		r_wb_sio_ack;
	reg	[31:0]	r_wb_sio_data;

	assign	wb_sio_stall = 1'b0;

	initial r_wb_sio_ack = 1'b0;
	always	@(posedge i_clk)
		r_wb_sio_ack <= (wb_sio_stb);
	assign	wb_sio_ack = r_wb_sio_ack;

	always	@(posedge i_clk)
	casez( wb_sio_addr[3:0] )
		4'h0: r_wb_sio_data <= wb_buildtime_idata;
		4'h1: r_wb_sio_data <= wb_buserr_idata;
		4'h2: r_wb_sio_data <= wb_buspic_idata;
		4'h3: r_wb_sio_data <= wb_genclk_idata;
		4'h4: r_wb_sio_data <= wb_genclk_test_idata;
		4'h5: r_wb_sio_data <= wb_gpio_idata;
		4'h6: r_wb_sio_data <= wb_netclockctr_idata;
		4'h7: r_wb_sio_data <= wb_nettxctr_idata;
		4'h8: r_wb_sio_data <= wb_pwrcount_idata;
		4'h9: r_wb_sio_data <= wb_rtcdate_idata;
		4'ha: r_wb_sio_data <= wb_spio_idata;
		4'hb: r_wb_sio_data <= wb_subseconds_idata;
		4'hc: r_wb_sio_data <= wb_sysclk_idata;
		4'hd: r_wb_sio_data <= wb_version_idata;
		default: r_wb_sio_data <= wb_version_idata;
	endcase
	assign	wb_sio_idata = r_wb_sio_data;


	//
	// Now to translate this logic to the various SIO slaves
	//
	// In this case, the SIO bus has the prefix wb_sio
	// and all of the slaves have various wires beginning
	// with their own respective bus prefixes.
	// Our goal here is to make certain that all of
	// the slave bus inputs match the SIO bus wires
	assign	wb_buildtime_cyc = wb_sio_cyc;
	assign	wb_buildtime_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h0);  // 0x0000000
	assign	wb_buildtime_we  = wb_sio_we;
	assign	wb_buildtime_data= wb_sio_data;
	assign	wb_buildtime_sel = wb_sio_sel;
	assign	wb_buserr_cyc = wb_sio_cyc;
	assign	wb_buserr_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h1);  // 0x0000004
	assign	wb_buserr_we  = wb_sio_we;
	assign	wb_buserr_data= wb_sio_data;
	assign	wb_buserr_sel = wb_sio_sel;
	assign	wb_buspic_cyc = wb_sio_cyc;
	assign	wb_buspic_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h2);  // 0x0000008
	assign	wb_buspic_we  = wb_sio_we;
	assign	wb_buspic_data= wb_sio_data;
	assign	wb_buspic_sel = wb_sio_sel;
	assign	wb_genclk_cyc = wb_sio_cyc;
	assign	wb_genclk_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h3);  // 0x000000c
	assign	wb_genclk_we  = wb_sio_we;
	assign	wb_genclk_data= wb_sio_data;
	assign	wb_genclk_sel = wb_sio_sel;
	assign	wb_genclk_test_cyc = wb_sio_cyc;
	assign	wb_genclk_test_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h4);  // 0x0000010
	assign	wb_genclk_test_we  = wb_sio_we;
	assign	wb_genclk_test_data= wb_sio_data;
	assign	wb_genclk_test_sel = wb_sio_sel;
	assign	wb_gpio_cyc = wb_sio_cyc;
	assign	wb_gpio_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h5);  // 0x0000014
	assign	wb_gpio_we  = wb_sio_we;
	assign	wb_gpio_data= wb_sio_data;
	assign	wb_gpio_sel = wb_sio_sel;
	assign	wb_netclockctr_cyc = wb_sio_cyc;
	assign	wb_netclockctr_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h6);  // 0x0000018
	assign	wb_netclockctr_we  = wb_sio_we;
	assign	wb_netclockctr_data= wb_sio_data;
	assign	wb_netclockctr_sel = wb_sio_sel;
	assign	wb_nettxctr_cyc = wb_sio_cyc;
	assign	wb_nettxctr_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h7);  // 0x000001c
	assign	wb_nettxctr_we  = wb_sio_we;
	assign	wb_nettxctr_data= wb_sio_data;
	assign	wb_nettxctr_sel = wb_sio_sel;
	assign	wb_pwrcount_cyc = wb_sio_cyc;
	assign	wb_pwrcount_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h8);  // 0x0000020
	assign	wb_pwrcount_we  = wb_sio_we;
	assign	wb_pwrcount_data= wb_sio_data;
	assign	wb_pwrcount_sel = wb_sio_sel;
	assign	wb_rtcdate_cyc = wb_sio_cyc;
	assign	wb_rtcdate_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'h9);  // 0x0000024
	assign	wb_rtcdate_we  = wb_sio_we;
	assign	wb_rtcdate_data= wb_sio_data;
	assign	wb_rtcdate_sel = wb_sio_sel;
	assign	wb_spio_cyc = wb_sio_cyc;
	assign	wb_spio_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'ha);  // 0x0000028
	assign	wb_spio_we  = wb_sio_we;
	assign	wb_spio_data= wb_sio_data;
	assign	wb_spio_sel = wb_sio_sel;
	assign	wb_subseconds_cyc = wb_sio_cyc;
	assign	wb_subseconds_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'hb);  // 0x000002c
	assign	wb_subseconds_we  = wb_sio_we;
	assign	wb_subseconds_data= wb_sio_data;
	assign	wb_subseconds_sel = wb_sio_sel;
	assign	wb_sysclk_cyc = wb_sio_cyc;
	assign	wb_sysclk_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'hc);  // 0x0000030
	assign	wb_sysclk_we  = wb_sio_we;
	assign	wb_sysclk_data= wb_sio_data;
	assign	wb_sysclk_sel = wb_sio_sel;
	assign	wb_version_cyc = wb_sio_cyc;
	assign	wb_version_stb = wb_sio_stb && (wb_sio_addr[ 3: 0] ==  4'hd);  // 0x0000034
	assign	wb_version_we  = wb_sio_we;
	assign	wb_version_data= wb_sio_data;
	assign	wb_version_sel = wb_sio_sel;
	//
	// wb Bus logic to handle 5 DOUBLE slaves
	//
	//
	reg	[1:0]	r_wb_dio_ack;
	// # dlist = 5, nextlg(#dlist) = 3
	reg	[2:0]	r_wb_dio_bus_select;
	reg	[31:0]	r_wb_dio_data;

	// DOUBLE peripherals are not allowed to stall.
	assign	wb_dio_stall = 1'b0;

	// DOUBLE peripherals return their acknowledgments in two
	// clocks--always, allowing us to collect this logic together
	// in a slave independent manner.  Here, the acknowledgment
	// is treated as a two stage shift register, cleared on any
	// reset, or any time the cycle line drops.  (Dropping the
	// cycle line aborts the transaction.)
	initial	r_wb_dio_ack = 0;
	always	@(posedge i_clk)
	if (i_reset || !wb_dio_cyc)
		r_wb_dio_ack <= 0;
	else
		r_wb_dio_ack <= { r_wb_dio_ack[0], (wb_dio_stb) };
	assign	wb_dio_ack = r_wb_dio_ack[1];

	// Since it costs us two clocks to go through this
	// logic, we'll take one of those clocks here to set
	// a selection index, and then on the next clock we'll
	// use this index to select from among the vaious
	// possible bus return values
	always @(posedge i_clk)
	casez(wb_dio_addr[5:3])
	3'b000: r_wb_dio_bus_select <= 3'd0;
	3'b001: r_wb_dio_bus_select <= 3'd1;
	3'b010: r_wb_dio_bus_select <= 3'd2;
	3'b011: r_wb_dio_bus_select <= 3'd3;
	3'b10?: r_wb_dio_bus_select <= 3'd4;
	default: r_wb_dio_bus_select <= 0;
	endcase

	always	@(posedge i_clk)
	casez(r_wb_dio_bus_select)
	3'd0: r_wb_dio_data <= wb_gck_idata;
	3'd1: r_wb_dio_data <= wb_rtc_idata;
	3'd2: r_wb_dio_data <= wb_gtb_idata;
	3'd3: r_wb_dio_data <= wb_netp_idata;
	3'd4: r_wb_dio_data <= wb_sio_idata;
	default: r_wb_dio_data <= wb_sio_idata;
	endcase

	assign	wb_dio_idata = r_wb_dio_data;

	assign	wb_gck_cyc = wb_dio_cyc;
	assign	wb_gck_stb = wb_dio_stb && ((wb_dio_addr[ 5: 3] &  3'h7) ==  3'h0);  // 0x0000000 - 0x000000f
	assign	wb_gck_we  = wb_dio_we;
	assign	wb_gck_addr= wb_dio_addr;
	assign	wb_gck_data= wb_dio_data;
	assign	wb_gck_sel = wb_dio_sel;
	assign	wb_rtc_cyc = wb_dio_cyc;
	assign	wb_rtc_stb = wb_dio_stb && ((wb_dio_addr[ 5: 3] &  3'h7) ==  3'h1);  // 0x0000020 - 0x000002f
	assign	wb_rtc_we  = wb_dio_we;
	assign	wb_rtc_addr= wb_dio_addr;
	assign	wb_rtc_data= wb_dio_data;
	assign	wb_rtc_sel = wb_dio_sel;
	assign	wb_gtb_cyc = wb_dio_cyc;
	assign	wb_gtb_stb = wb_dio_stb && ((wb_dio_addr[ 5: 3] &  3'h7) ==  3'h2);  // 0x0000040 - 0x000005f
	assign	wb_gtb_we  = wb_dio_we;
	assign	wb_gtb_addr= wb_dio_addr;
	assign	wb_gtb_data= wb_dio_data;
	assign	wb_gtb_sel = wb_dio_sel;
	assign	wb_netp_cyc = wb_dio_cyc;
	assign	wb_netp_stb = wb_dio_stb && ((wb_dio_addr[ 5: 3] &  3'h7) ==  3'h3);  // 0x0000060 - 0x000007f
	assign	wb_netp_we  = wb_dio_we;
	assign	wb_netp_addr= wb_dio_addr;
	assign	wb_netp_data= wb_dio_data;
	assign	wb_netp_sel = wb_dio_sel;
	assign	wb_sio_cyc = wb_dio_cyc;
	assign	wb_sio_stb = wb_dio_stb && ((wb_dio_addr[ 5: 3] &  3'h6) ==  3'h4);  // 0x0000080 - 0x00000bf
	assign	wb_sio_we  = wb_dio_we;
	assign	wb_sio_addr= wb_dio_addr;
	assign	wb_sio_data= wb_dio_data;
	assign	wb_sio_sel = wb_dio_sel;
	assign	wb_flashcfg_err= 1'b0;
	assign	wb_zipscope_err= 1'b0;
	assign	wb_gpsu_err= 1'b0;
	assign	wb_sdcard_err= 1'b0;
	assign	wb_uart_err= 1'b0;
	assign	wb_cfg_err= 1'b0;
	assign	wb_mdio_err= 1'b0;
	assign	wb_dio_err= 1'b0;
	assign	wb_netb_err= 1'b0;
	assign	wb_bkram_err= 1'b0;
	assign	wb_flash_err= 1'b0;
	// info: @ERROR.WIRE for xpand matches the buses error name, wb_xpand_err
	//
	// Connect the wb bus components together using the wbxbar()
	//
	//
	wbxbar #(
		.NM(2), .NS(12), .AW(28), .DW(32),
		.SLAVE_ADDR({
			{ 28'h8000000 }, //    xpand: 0x20000000
			{ 28'h5800000 }, //    flash: 0x16000000
			{ 28'h5000000 }, //    bkram: 0x14000000
			{ 28'h4800000 }, //     netb: 0x12000000
			{ 28'h4000000 }, //   wb_dio: 0x10000000
			{ 28'h3800000 }, //     mdio: 0x0e000000
			{ 28'h3000000 }, //      cfg: 0x0c000000
			{ 28'h2800000 }, //     uart: 0x0a000000
			{ 28'h2000000 }, //   sdcard: 0x08000000
			{ 28'h1800000 }, //     gpsu: 0x06000000
			{ 28'h1000000 }, // zipscope: 0x04000000
			{ 28'h0800000 }  // flashcfg: 0x02000000
		}),
		.SLAVE_MASK({
			{ 28'h8000000 }, //    xpand
			{ 28'hf800000 }, //    flash
			{ 28'hf800000 }, //    bkram
			{ 28'hf800000 }, //     netb
			{ 28'hf800000 }, //   wb_dio
			{ 28'hf800000 }, //     mdio
			{ 28'hf800000 }, //      cfg
			{ 28'hf800000 }, //     uart
			{ 28'hf800000 }, //   sdcard
			{ 28'hf800000 }, //     gpsu
			{ 28'hf800000 }, // zipscope
			{ 28'hf800000 }  // flashcfg
		}))
	wb_xbar(
		.i_clk(i_clk), .i_reset(i_reset),
		.i_mcyc({
			wb_wbu_arbiter_cyc,
			wb_zip_cyc
		}),
		.i_mstb({
			wb_wbu_arbiter_stb,
			wb_zip_stb
		}),
		.i_mwe({
			wb_wbu_arbiter_we,
			wb_zip_we
		}),
		.i_maddr({
			wb_wbu_arbiter_addr,
			wb_zip_addr
		}),
		.i_mdata({
			wb_wbu_arbiter_data,
			wb_zip_data
		}),
		.i_msel({
			wb_wbu_arbiter_sel,
			wb_zip_sel
		}),
		.o_mstall({
			wb_wbu_arbiter_stall,
			wb_zip_stall
		}),
		.o_mack({
			wb_wbu_arbiter_ack,
			wb_zip_ack
		}),
		.o_mdata({
			wb_wbu_arbiter_idata,
			wb_zip_idata
		}),
		.o_merr({
			wb_wbu_arbiter_err,
			wb_zip_err
		}),
		// Slave connections
		.o_scyc({
			wb_xpand_cyc,
			wb_flash_cyc,
			wb_bkram_cyc,
			wb_netb_cyc,
			wb_dio_cyc,
			wb_mdio_cyc,
			wb_cfg_cyc,
			wb_uart_cyc,
			wb_sdcard_cyc,
			wb_gpsu_cyc,
			wb_zipscope_cyc,
			wb_flashcfg_cyc
		}),
		.o_sstb({
			wb_xpand_stb,
			wb_flash_stb,
			wb_bkram_stb,
			wb_netb_stb,
			wb_dio_stb,
			wb_mdio_stb,
			wb_cfg_stb,
			wb_uart_stb,
			wb_sdcard_stb,
			wb_gpsu_stb,
			wb_zipscope_stb,
			wb_flashcfg_stb
		}),
		.o_swe({
			wb_xpand_we,
			wb_flash_we,
			wb_bkram_we,
			wb_netb_we,
			wb_dio_we,
			wb_mdio_we,
			wb_cfg_we,
			wb_uart_we,
			wb_sdcard_we,
			wb_gpsu_we,
			wb_zipscope_we,
			wb_flashcfg_we
		}),
		.o_saddr({
			wb_xpand_addr,
			wb_flash_addr,
			wb_bkram_addr,
			wb_netb_addr,
			wb_dio_addr,
			wb_mdio_addr,
			wb_cfg_addr,
			wb_uart_addr,
			wb_sdcard_addr,
			wb_gpsu_addr,
			wb_zipscope_addr,
			wb_flashcfg_addr
		}),
		.o_sdata({
			wb_xpand_data,
			wb_flash_data,
			wb_bkram_data,
			wb_netb_data,
			wb_dio_data,
			wb_mdio_data,
			wb_cfg_data,
			wb_uart_data,
			wb_sdcard_data,
			wb_gpsu_data,
			wb_zipscope_data,
			wb_flashcfg_data
		}),
		.o_ssel({
			wb_xpand_sel,
			wb_flash_sel,
			wb_bkram_sel,
			wb_netb_sel,
			wb_dio_sel,
			wb_mdio_sel,
			wb_cfg_sel,
			wb_uart_sel,
			wb_sdcard_sel,
			wb_gpsu_sel,
			wb_zipscope_sel,
			wb_flashcfg_sel
		}),
		.i_sstall({
			wb_xpand_stall,
			wb_flash_stall,
			wb_bkram_stall,
			wb_netb_stall,
			wb_dio_stall,
			wb_mdio_stall,
			wb_cfg_stall,
			wb_uart_stall,
			wb_sdcard_stall,
			wb_gpsu_stall,
			wb_zipscope_stall,
			wb_flashcfg_stall
		}),
		.i_sack({
			wb_xpand_ack,
			wb_flash_ack,
			wb_bkram_ack,
			wb_netb_ack,
			wb_dio_ack,
			wb_mdio_ack,
			wb_cfg_ack,
			wb_uart_ack,
			wb_sdcard_ack,
			wb_gpsu_ack,
			wb_zipscope_ack,
			wb_flashcfg_ack
		}),
		.i_sdata({
			wb_xpand_idata,
			wb_flash_idata,
			wb_bkram_idata,
			wb_netb_idata,
			wb_dio_idata,
			wb_mdio_idata,
			wb_cfg_idata,
			wb_uart_idata,
			wb_sdcard_idata,
			wb_gpsu_idata,
			wb_zipscope_idata,
			wb_flashcfg_idata
		}),
		.i_serr({
			wb_xpand_err,
			wb_flash_err,
			wb_bkram_err,
			wb_netb_err,
			wb_dio_err,
			wb_mdio_err,
			wb_cfg_err,
			wb_uart_err,
			wb_sdcard_err,
			wb_gpsu_err,
			wb_zipscope_err,
			wb_flashcfg_err
		})
		);

	//
	// BUS-LOGIC for wbu
	//
	//
	// No class SINGLE peripherals on the "wbu" bus
	//

	//
	// No class DOUBLE peripherals on the "wbu" bus
	//

	// info: @ERROR.WIRE for wbu_arbiter matches the buses error name, wbu_wbu_arbiter_err
	assign	wbu_zip_err= 1'b0;
	//
	// Connect the wbu bus components together using the wbxbar()
	//
	//
	wbxbar #(
		.NM(1), .NS(2), .AW(29), .DW(32),
		.SLAVE_ADDR({
			{ 29'h10000000 }, //         zip: 0x40000000
			{ 29'h00000000 }  // wbu_arbiter: 0x00000000
		}),
		.SLAVE_MASK({
			{ 29'h18000000 }, //         zip
			{ 29'h10000000 }  // wbu_arbiter
		}))
	wbu_xbar(
		.i_clk(i_clk), .i_reset(i_reset),
		.i_mcyc({
			wbu_wbu_cyc
		}),
		.i_mstb({
			wbu_wbu_stb
		}),
		.i_mwe({
			wbu_wbu_we
		}),
		.i_maddr({
			wbu_wbu_addr
		}),
		.i_mdata({
			wbu_wbu_data
		}),
		.i_msel({
			wbu_wbu_sel
		}),
		.o_mstall({
			wbu_wbu_stall
		}),
		.o_mack({
			wbu_wbu_ack
		}),
		.o_mdata({
			wbu_wbu_idata
		}),
		.o_merr({
			wbu_wbu_err
		}),
		// Slave connections
		.o_scyc({
			wbu_zip_cyc,
			wbu_wbu_arbiter_cyc
		}),
		.o_sstb({
			wbu_zip_stb,
			wbu_wbu_arbiter_stb
		}),
		.o_swe({
			wbu_zip_we,
			wbu_wbu_arbiter_we
		}),
		.o_saddr({
			wbu_zip_addr,
			wbu_wbu_arbiter_addr
		}),
		.o_sdata({
			wbu_zip_data,
			wbu_wbu_arbiter_data
		}),
		.o_ssel({
			wbu_zip_sel,
			wbu_wbu_arbiter_sel
		}),
		.i_sstall({
			wbu_zip_stall,
			wbu_wbu_arbiter_stall
		}),
		.i_sack({
			wbu_zip_ack,
			wbu_wbu_arbiter_ack
		}),
		.i_sdata({
			wbu_zip_idata,
			wbu_wbu_arbiter_idata
		}),
		.i_serr({
			wbu_zip_err,
			wbu_wbu_arbiter_err
		})
		);

	//
	// BUS-LOGIC for rambus
	//
//
// Bus rambus has only one master (rambus_xpand) and one slave (rambus_sdram)
// connected to it -- skipping the interconnect
//
	assign	rambus_sdram_cyc  = rambus_xpand_cyc;
	assign	rambus_sdram_stb  = rambus_xpand_stb;
	assign	rambus_sdram_we   = rambus_xpand_we;
	assign	rambus_sdram_addr = rambus_xpand_addr;
	assign	rambus_sdram_data = rambus_xpand_data;
	assign	rambus_sdram_sel  = rambus_xpand_sel;
	assign	rambus_sdram_err = 1'b0;
	assign	rambus_xpand_err = rambus_sdram_err;
	assign	rambus_xpand_stall = rambus_sdram_stall;
	assign	rambus_xpand_ack   = rambus_sdram_ack;
	assign	rambus_xpand_idata = rambus_sdram_data;
	//
	// Declare the interrupt busses
	//
	// Interrupt busses are defined by anything with a @PIC tag.
	// The @PIC.BUS tag defines the name of the wire bus below,
	// while the @PIC.MAX tag determines the size of the bus width.
	//
	// For your peripheral to be assigned to this bus, it must have an
	// @INT.NAME.WIRE= tag to define the wire name of the interrupt line,
	// and an @INT.NAME.PIC= tag matching the @PIC.BUS tag of the bus
	// your interrupt will be assigned to.  If an @INT.NAME.ID tag also
	// exists, then your interrupt will be assigned to the position given
	// by the ID# in that tag.
	//
	assign	bus_int_vector = {
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		spio_int,
		sdcard_int
	};
	assign	alt_int_vector = {
		uarttx_int,
		rtc_int,
		gpsutxf_int,
		gpsurxf_int,
		gpsutx_int,
		gpsurx_int,
		gpio_int,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0
	};
	assign	sys_int_vector = {
		1'b0,
		1'b0,
		uartrxf_int,
		uarttxf_int,
		sdcard_int,
		netrx_int,
		nettx_int,
		ck_pps,
		w_bus_int,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0
	};


	//
	//
	// Now we turn to defining all of the parts and pieces of what
	// each of the various peripherals does, and what logic it needs.
	//
	// This information comes from the @MAIN.INSERT and @MAIN.ALT tags.
	// If an @ACCESS tag is available, an ifdef is created to handle
	// having the access and not.  If the @ACCESS tag is `defined above
	// then the @MAIN.INSERT code is executed.  If not, the @MAIN.ALT
	// code is exeucted, together with any other cleanup settings that
	// might need to take place--such as returning zeros to the bus,
	// or making sure all of the various interrupt wires are set to
	// zero if the component is not included.
	//
	clkcounter clksysclkctr(i_clk, ck_pps, i_clk, wb_sysclk_idata);

	initial	r_sysclk_ack = 0;
	always @(posedge i_clk)
		r_sysclk_ack <= (wb_sysclk_stb);
	assign	wb_sysclk_ack   = r_sysclk_ack;
	assign	wb_sysclk_stall = 1'b0;
`ifdef	GPSTRK_ACCESS
	// Verilator lint_off UNUSED
	wire	[1:0]	ck_dbg;
	// Verilator lint_on  UNUSED

	gpsclock #(.DEFAULT_STEP(GPSCLOCK_DEFAULT_STEP))
		ppsck(i_clk, 1'b0, gps_pps, ck_pps, gps_led,
			wb_gck_cyc, wb_gck_stb, wb_gck_we,
			wb_gck_addr[2-1:0],
			wb_gck_data, // 32 bits wide
			wb_gck_sel,  // 32/8 bits wide
		wb_gck_stall, wb_gck_ack, wb_gck_idata,
			gps_tracking, gps_now, gps_step, gps_err, gps_locked,
			ck_dbg);
`else	// GPSTRK_ACCESS
	wire	[31:0]	pre_step;
	assign	pre_step = { 16'h00, (({GPSCLOCK_DEFAULT_STEP[27:0],20'h00})
				>>GPSCLOCK_DEFAULT_STEP[31:28]) };
	always @(posedge i_clk)
		{ ck_pps, gps_step[31:0] } <= gps_step + pre_step;
	assign	gck_stall  = 1'b0;
	assign	gps_now    = 64'h0;
	assign	gps_err    = 64'h0;
	assign	gps_step   = 64'h0;
	assign	gps_led    = 1'b0;
	assign	gps_locked = 1'b0;

	assign	ck_pps = 1'b0;	// gck.INT.PPS.WIRE
`endif	// GPSTRK_ACCESS

`ifdef	GPSTRK_ACCESS
	gpsclock_tb #(.CLOCK_FREQUENCY_HZ(100000000))
		ppstb(i_clk, ck_pps, tb_pps,
			wb_gtb_cyc, wb_gtb_stb, wb_gtb_we,
			wb_gtb_addr[3-1:0],
			wb_gtb_data, // 32 bits wide
			wb_gtb_sel,  // 32/8 bits wide
		wb_gtb_stall, wb_gtb_ack, wb_gtb_idata,
			gps_err, gps_now, gps_step);

`ifdef	GPSTB
	assign	gps_pps = tb_pps;
`else
	assign	gps_pps = i_gps_pps;
`endif

`endif

`ifndef	ETHERNET_ACCESS
	// Ethernet packet memory declaration
	//
	// The only time this needs to be defined is when the ethernet module
	// itself isnt defined.  Otherwise, the access is accomplished by the
	// ethernet module

	memdev #(14)
		enet_buffers(i_clk,
			wb_netb_cyc, wb_netb_stb, wb_netb_we,
			wb_netb_addr[13-1:0],
			wb_netb_data, // 32 bits wide
			wb_netb_sel,  // 32/8 bits wide
		wb_netb_stall, wb_netb_ack, wb_netb_idata);

`else

// These don't need to be defined here, and it deed should not be defined here
// lest their definitions override those of the netb interface defined in the
// enetpackets module
//
//	assign	wb_netb_ack   = 1'b0;
//	assign	wb_netb_stall = 1'b0;
//	assign	wb_netb_data  = wb_netp_data;

`endif

`ifdef	ETHERNET_ACCESS
	enetpackets	#(.MEMORY_ADDRESS_WIDTH(14))
		netctrl(i_clk, i_reset,
			wb_netb_cyc, wb_netb_stb, wb_netb_we,
			wb_netb_addr[13-1:0],
			wb_netb_data, // 32 bits wide
			wb_netb_sel,  // 32/8 bits wide
		wb_netb_stall, wb_netb_ack, wb_netb_idata,
			wb_netp_cyc, wb_netp_stb, wb_netp_we,
			wb_netp_addr[3-1:0],
			wb_netp_data, // 32 bits wide
			wb_netp_sel,  // 32/8 bits wide
		wb_netp_stall, wb_netp_ack, wb_netp_idata,
			o_net_reset_n,
			i_net_rx_clk, i_net_rx_dv, i_net_rx_err, i_net_rxd,
			i_clk_125mhz, o_net_tx_clk, o_net_tx_ctl, o_net_txd,
			netrx_int, nettx_int, netp_debug_clk, netp_debug);

`else	// ETHERNET_ACCESS
	assign	nettx_int = 1'b0;	// netp.INT.NETTX.WIRE
	assign	netrx_int = 1'b0;	// netp.INT.NETRX.WIRE
`endif	// ETHERNET_ACCESS

`ifdef	INCLUDE_ZIPCPU
	//
	//
	// The ZipCPU/ZipSystem BUS master
	//
	//
	assign	zip_int_vector = { alt_int_vector[14:8], sys_int_vector[14:6] };
	zipsystem #(.RESET_ADDRESS(RESET_ADDRESS),
			.ADDRESS_WIDTH(ZIP_ADDRESS_WIDTH),
			.LGICACHE(12),.LGDCACHE(12),
			.START_HALTED(ZIP_START_HALTED),
`ifdef	VERILATOR
			.RESET_DURATION(20),
`else
			.RESET_DURATION(20_000),
`endif
			.EXTERNAL_INTERRUPTS(ZIP_INTS))
		swic(i_clk, (i_reset)||(i_cpu_reset),
			// Zippys wishbone interface
			wb_zip_cyc, wb_zip_stb, wb_zip_we,
			wb_zip_addr[28-1:0],
			wb_zip_data, // 32 bits wide
			wb_zip_sel,  // 32/8 bits wide
		wb_zip_stall,wb_zip_ack, wb_zip_idata,wb_zip_err,
			zip_int_vector, zip_cpu_int,
			// Debug wishbone interface
			wbu_zip_cyc, wbu_zip_stb, wbu_zip_we,
			wbu_zip_addr[1-1:0],
			wbu_zip_data, // 32 bits wide
			wbu_zip_sel,  // 32/8 bits wide
		wbu_zip_stall, wbu_zip_ack, wbu_zip_idata,
			zip_debug);
	assign	zip_trigger = zip_debug[31];
`else	// INCLUDE_ZIPCPU

	//
	// In the case that there is no zip peripheral
	// responding on the wbu bus
	assign	zip_ack   = 1'b0;
	assign	zip_err   = (zip_stb);
	assign	zip_stall = 0;
	assign	zip_data  = 0;

	assign	zip_cpu_int = 1'b0;	// zip.INT.ZIP.WIRE
`endif	// INCLUDE_ZIPCPU

	assign	wb_version_idata = `DATESTAMP;
	assign	wb_version_ack = wb_version_stb;
	assign	wb_version_stall = 1'b0;
`ifdef	GPIO_ACCESS
	//
	// GPIO
	//
	// This interface should allow us to control up to 16 GPIO inputs, and
	// another 16 GPIO outputs.  The interrupt trips when any of the inputs
	// changes.  (Sorry, which input isn't (yet) selectable.)
	//
	localparam	INITIAL_GPIO = 16'h04f;
	wbgpio	#(NGPI, NGPO, INITIAL_GPIO)
		gpioi(i_clk, wb_gpio_cyc, wb_gpio_stb, wb_gpio_we,
			wb_gpio_data, // 32 bits wide
			wb_gpio_sel,  // 32/8 bits wide
		wb_gpio_stall, wb_gpio_ack, wb_gpio_idata,
			i_gpio, o_gpio, gpio_int);

	assign	sd_reset = o_gpio[6];
`else	// GPIO_ACCESS
	assign	gpio_int = 1'b0;	// gpio.INT.GPIO.WIRE
`endif	// GPIO_ACCESS

`ifdef	FLASHCFG_ACCESS
	// The Flash control interface is defined by the flash instantiation
	// hence we don't need to do anything to define it here.
`else	// FLASHCFG_ACCESS

	//
	// In the case that there is no flashcfg peripheral
	// responding on the wb bus
	assign	flashcfg_ack   = 1'b0;
	assign	flashcfg_err   = (flashcfg_stb);
	assign	flashcfg_stall = 0;
	assign	flashcfg_data  = 0;

`endif	// FLASHCFG_ACCESS

`ifdef	ZIPSCOPE_SCOPE
	wbscope #(.LGMEM(13),
		.SYNCHRONOUS(1))
	zipscopei(i_clk, 1'b1, zip_trigger, zip_debug,
		i_clk, wb_zipscope_cyc, wb_zipscope_stb, wb_zipscope_we,
			wb_zipscope_addr[1-1:0],
			wb_zipscope_data, // 32 bits wide
			wb_zipscope_sel,  // 32/8 bits wide
		wb_zipscope_stall, wb_zipscope_ack, wb_zipscope_idata,
		zipscope_int);
`else	// ZIPSCOPE_SCOPE
	assign	zipscope_int = 0;

	//
	// In the case that there is no zipscope peripheral
	// responding on the wb bus
	assign	zipscope_ack   = 1'b0;
	assign	zipscope_err   = (zipscope_stb);
	assign	zipscope_stall = 0;
	assign	zipscope_data  = 0;

`endif	// ZIPSCOPE_SCOPE

`ifdef	WBUBUS_MASTER
	// The Host USB interface, to be used by the WB-UART bus
	rxuartlite	#(.TIMER_BITS(DBGBUSBITS),
				.CLOCKS_PER_BAUD(BUSUART[DBGBUSBITS-1:0]))
		rcv(i_clk, i_wbu_uart_rx,
				wbu_rx_stb, wbu_rx_data);
	txuartlite	#(.TIMING_BITS(DBGBUSBITS[4:0]),
				.CLOCKS_PER_BAUD(BUSUART[DBGBUSBITS-1:0]))
		txv(i_clk,
				wbu_tx_stb,
				wbu_tx_data,
				o_wbu_uart_tx,
				wbu_tx_busy);

`ifdef	INCLUDE_ZIPCPU
`else
	assign	zip_dbg_ack   = 1'b0;
	assign	zip_dbg_stall = 1'b0;
	assign	zip_dbg_data  = 0;
`endif
`ifndef	BUSPIC_ACCESS
	wire	w_bus_int;
	assign	w_bus_int = 1'b0;
`endif
	// Verilator lint_off UNUSED
	wire	[31:0]	wbu_wbu_tmp_addr;
	// Verilator lint_on  UNUSED
	wbuconsole #(.LGWATCHDOG(DBGBUSWATCHDOG))
	genbus(i_clk, wbu_rx_stb, wbu_rx_data,
			wbu_wbu_cyc, wbu_wbu_stb, wbu_wbu_we, wbu_wbu_tmp_addr, wbu_wbu_data,
			wbu_wbu_stall, wbu_wbu_ack,
			wbu_wbu_err, wbu_wbu_idata,
			w_bus_int,
			wbu_tx_stb, wbu_tx_data, wbu_tx_busy,
			//
			w_console_tx_stb, w_console_tx_data, w_console_busy,
			w_console_rx_stb, w_console_rx_data,
			//
			wbubus_dbg[0]);
	assign	wbu_wbu_sel = 4'hf;
	assign	wbu_wbu_addr = wbu_wbu_tmp_addr[(29-1):0];
`else	// WBUBUS_MASTER
`endif	// WBUBUS_MASTER

	always @(posedge i_clk)
	if (wb_zip_err)
	begin
		r_buserr_addr <= 0;
		r_buserr_addr[28-1:0] <= wb_zip_addr[28-1:0];
	end else if (wbu_wbu_err)
	begin
		r_buserr_addr <= 0;
		r_buserr_addr[29-1:0] <= wbu_wbu_addr[29-1:0];
	end
	assign	wb_buserr_stall= 1'b0;
	assign	wb_buserr_ack  = wb_buserr_stb;
	assign	wb_buserr_idata = { {(30-29){1'b0}},
			r_buserr_addr, 2'b00 };
`ifdef	SDRAM_ACCESS
	assign	o_sdram_cyc  = rambus_sdram_cyc;
	assign	o_sdram_stb  =(rambus_sdram_stb);
	assign	o_sdram_we   = rambus_sdram_we;
	assign	o_sdram_addr = rambus_sdram_addr[25-1:0];
	assign	o_sdram_data = rambus_sdram_data;
	assign	o_sdram_sel  = rambus_sdram_sel;
	assign	rambus_sdram_ack   = i_sdram_ack;
	assign	rambus_sdram_stall = i_sdram_stall;
	assign	rambus_sdram_idata = i_sdram_data;

`else	// SDRAM_ACCESS

	//
	// In the case that there is no sdram peripheral
	// responding on the rambus bus
	assign	sdram_ack   = 1'b0;
	assign	sdram_err   = (sdram_stb);
	assign	sdram_stall = 0;
	assign	sdram_data  = 0;

`endif	// SDRAM_ACCESS

`ifdef	CFG_ACCESS
`ifdef	VERILATOR
	reg	r_cfg_ack;

	initial	r_cfg_ack = 1'b0;
	always @(posedge i_clk)
		r_cfg_ack <= wb_cfg_stb;
	assign	wb_cfg_ack   = r_cfg_ack;
	assign	wb_cfg_stall = 1'b0;
	assign	wb_cfg_idata = 32'h00;
`else
	wbicapetwo #(ICAPE_LGDIV)
		cfgport(i_clk, wb_cfg_cyc, wb_cfg_stb, wb_cfg_we,
			wb_cfg_addr[5-1:0],
			wb_cfg_data, // 32 bits wide
			wb_cfg_sel,  // 32/8 bits wide
		wb_cfg_stall, wb_cfg_ack, wb_cfg_idata);
`endif
`else	// CFG_ACCESS

	//
	// In the case that there is no cfg peripheral
	// responding on the wb bus
	assign	cfg_ack   = 1'b0;
	assign	cfg_err   = (cfg_stb);
	assign	cfg_stall = 0;
	assign	cfg_data  = 0;

`endif	// CFG_ACCESS

	assign	wb_wbu_arbiter_cyc  = wbu_wbu_arbiter_cyc;
	assign	wb_wbu_arbiter_stb  = wbu_wbu_arbiter_stb;
	assign	wb_wbu_arbiter_we   = wbu_wbu_arbiter_we;
	assign	wb_wbu_arbiter_addr = wbu_wbu_arbiter_addr[28-1:0];
	assign	wb_wbu_arbiter_data = wbu_wbu_arbiter_data;
	assign	wb_wbu_arbiter_sel  = wbu_wbu_arbiter_sel;
	//
	assign	wbu_wbu_arbiter_stall = wb_wbu_arbiter_stall;
	assign	wbu_wbu_arbiter_ack   = wb_wbu_arbiter_ack;
	assign	wbu_wbu_arbiter_idata = wb_wbu_arbiter_idata;
	assign	wbu_wbu_arbiter_err   = wb_wbu_arbiter_err;

	assign	wb_buildtime_idata = `BUILDTIME;
	assign	wb_buildtime_ack = wb_buildtime_stb;
	assign	wb_buildtime_stall = 1'b0;
`ifdef	FLASH_ACCESS
	qflexpress #(.LGFLASHSZ(24), .OPT_CLKDIV(1),
		.NDUMMY(6), .RDDELAY(1),
		.OPT_STARTUP_FILE("spansion.hex"),
`ifdef	FLASHCFG_ACCESS
		.OPT_CFG(1'b1)
`else
		.OPT_CFG(1'b0)
`endif
		)
		flashi(i_clk, i_reset,
			// Primary memory reading inputs
			wb_flash_cyc, wb_flash_stb, wb_flash_we,
			wb_flash_addr[22-1:0],
			wb_flash_data, // 32 bits wide
			wb_flash_sel,  // 32/8 bits wide
		wb_flash_stall, wb_flash_ack, wb_flash_idata,
			// Configuration bus ports
			wb_flashcfg_cyc, wb_flashcfg_stb, wb_flashcfg_we,
			wb_flashcfg_data, // 32 bits wide
			wb_flashcfg_sel,  // 32/8 bits wide
		wb_flashcfg_stall, wb_flashcfg_ack, wb_flashcfg_idata,
			o_qspi_sck, o_qspi_cs_n, o_qspi_mod, o_qspi_dat, i_qspi_dat,
			flash_dbg_trigger, flash_debug);
`else	// FLASH_ACCESS
	assign	o_qspi_sck  = 1'b1;
	assign	o_qspi_cs_n = 1'b1;
	assign	o_qspi_mod  = 2'b01;
	assign	o_qspi_dat  = 4'b1111;

	//
	// In the case that there is no flash peripheral
	// responding on the wb bus
	assign	flash_ack   = 1'b0;
	assign	flash_err   = (flash_stb);
	assign	flash_stall = 0;
	assign	flash_data  = 0;

`endif	// FLASH_ACCESS

`ifdef	GPSUART_ACCESS
	wbuart #(.INITIAL_SETUP(31'h000028b0))
 		gpsu_uart(i_clk, 1'b0,
			wb_gpsu_cyc, wb_gpsu_stb, wb_gpsu_we,
			wb_gpsu_addr[2-1:0],
			wb_gpsu_data, // 32 bits wide
			wb_gpsu_sel,  // 32/8 bits wide
		wb_gpsu_stall, wb_gpsu_ack, wb_gpsu_idata,
 			i_gpsu_rx, o_gpsu_tx, w_gpsu_cts_n, w_gpsu_rts_n,
			gpsurx_int, gpsutx_int,
			gpsurxf_int, gpsutxf_int);
`else	// GPSUART_ACCESS
	assign	o_gpsu_tx    = 1'b1;
	assign	w_gpsu_rts_n = 1'b0;

	//
	// In the case that there is no gpsu peripheral
	// responding on the wb bus
	assign	gpsu_ack   = 1'b0;
	assign	gpsu_err   = (gpsu_stb);
	assign	gpsu_stall = 0;
	assign	gpsu_data  = 0;

	assign	gpsutx_int = 1'b0;	// gpsu.INT.GPSTX.WIRE
	assign	gpsutxf_int = 1'b0;	// gpsu.INT.GPSTXF.WIRE
	assign	gpsurx_int = 1'b0;	// gpsu.INT.GPSRX.WIRE
	assign	gpsurxf_int = 1'b0;	// gpsu.INT.GPSRXF.WIRE
`endif	// GPSUART_ACCESS

`ifdef	BUSPIC_ACCESS
	//
	// The BUS Interrupt controller
	//
	icontrol #(15)	buspici(i_clk, 1'b0,
			wb_buspic_cyc, wb_buspic_stb, wb_buspic_we,
			wb_buspic_data, // 32 bits wide
			wb_buspic_sel,  // 32/8 bits wide
		wb_buspic_stall, wb_buspic_ack, wb_buspic_idata,
			bus_int_vector, w_bus_int);
`else	// BUSPIC_ACCESS
	assign	w_bus_int = 1'b0;	// buspic.INT.BUS.WIRE
`endif	// BUSPIC_ACCESS

	clkcounter clkgenclk_testctr(i_clk, ck_pps, i_genclk_clk, wb_genclk_test_idata);

	initial	r_genclk_test_ack = 0;
	always @(posedge i_clk)
		r_genclk_test_ack <= (wb_genclk_test_stb);
	assign	wb_genclk_test_ack   = r_genclk_test_ack;
	assign	wb_genclk_test_stall = 1'b0;
`ifdef	GPSTRK_ACCESS
	assign	wb_subseconds_idata = gps_now[31:0];
`else
	always @(posedge i_clk)
	if (wb_subseconds_stb && wb_subseconds_we)
		r_subseconds_data <= wb_data;
	else
		r_subseconds_data <= r_subseconds_data
			+ { 16'h0, RTLCLKSTEP[31:16] };

	assign	wb_subseconds_idata = r_subseconds_data;
`endif
`ifdef	ARBITRARY_CLOCK_GENERATOR_ACCESS
	initial	r_genclk_data = 31'd20;
	always @(posedge i_clk)
	if (wb_genclk_stb && wb_genclk_we)
		r_genclk_data <= wb_genclk_data[30:0];

	always @(posedge i_clk)
		r_genclk_ack <= (wb_genclk_stb)&&(wb_genclk_we);
	assign	wb_genclk_ack   = r_genclk_ack;
	assign	wb_genclk_stall = 1'b0;
	assign	wb_genclk_idata = { i_genclk_pll_locked, r_genclk_data };
	assign	o_genclk_ce = r_genclk_data[30];

	genclk	clock_generator(i_clk,
			{ 2'b00, r_genclk_data[29:0] },
			o_genclk_word,
			w_genclk_stb);
`else	// ARBITRARY_CLOCK_GENERATOR_ACCESS
`endif	// ARBITRARY_CLOCK_GENERATOR_ACCESS

`ifdef	NETTXCLK_ACCESS
	clkcounter clknettxctrctr(i_clk, ck_pps, i_clk_125mhz, wb_nettxctr_idata);

	initial	r_nettxctr_ack = 0;
	always @(posedge i_clk)
		r_nettxctr_ack <= (wb_nettxctr_stb);
	assign	wb_nettxctr_ack   = r_nettxctr_ack;
	assign	wb_nettxctr_stall = 1'b0;
`else	// NETTXCLK_ACCESS
`endif	// NETTXCLK_ACCESS

	assign	i_net_tx_clk = i_clk_125mhz;
`ifdef	RTC_ACCESS
`ifdef	GPSTRK_ACCESS
	rtcgps	#(RTC_CLKSTEP) thertc(i_clk, i_reset,
		wb_rtc_cyc, wb_rtc_stb, wb_rtc_we,
			wb_rtc_addr[2-1:0],
			wb_rtc_data, // 32 bits wide
			wb_rtc_sel,  // 32/8 bits wide
		wb_rtc_stall, wb_rtc_ack, wb_rtc_idata,
		rtc_int, rtc_ppd,
		gps_tracking, ck_pps, gps_step[47:16], rtc_pps);
`else
	rtclight #(32'h2af31d) thertc(i_clk, i_reset,
		wb_cyc, (wb_stb)&&(rtc_sel), wb_we, { 1'b0, wb_addr[1:0] },
			wb_data, wb_sel,
		rtc_stall, rtc_ack, rtc_data,
		rtc_int, rtc_ppd);
`endif
`else	// RTC_ACCESS
`ifdef	GPSTRK_ACCESS
	assign	rtc_pps = 1'b0;
`endif
	assign	rtc_ppd = 1'b0;
	assign	rtc_int = 1'b0;	// rtc.INT.RTC.WIRE
`endif	// RTC_ACCESS

`ifdef	BKRAM_ACCESS
	memdev #(.LGMEMSZ(20), .EXTRACLOCK(1))
		bkrami(i_clk, i_reset,
			wb_bkram_cyc, wb_bkram_stb, wb_bkram_we,
			wb_bkram_addr[18-1:0],
			wb_bkram_data, // 32 bits wide
			wb_bkram_sel,  // 32/8 bits wide
		wb_bkram_stall, wb_bkram_ack, wb_bkram_idata);
`else	// BKRAM_ACCESS

	//
	// In the case that there is no bkram peripheral
	// responding on the wb bus
	assign	bkram_ack   = 1'b0;
	assign	bkram_err   = (bkram_stb);
	assign	bkram_stall = 0;
	assign	bkram_data  = 0;

`endif	// BKRAM_ACCESS

`ifdef	NETCLOCKCTR_ACCESS
	clkcounter clknetclockctrctr(i_clk, ck_pps, i_net_rx_clk, wb_netclockctr_idata);

	initial	r_netclockctr_ack = 0;
	always @(posedge i_clk)
		r_netclockctr_ack <= (wb_netclockctr_stb);
	assign	wb_netclockctr_ack   = r_netclockctr_ack;
	assign	wb_netclockctr_stall = 1'b0;
`else	// NETCLOCKCTR_ACCESS
`endif	// NETCLOCKCTR_ACCESS

`ifdef	SDSPI_ACCESS
	// SPI mapping
	wire	w_sd_cs_n, w_sd_mosi, w_sd_miso;

	sdspi	sdcardi(i_clk, sd_reset,
		wb_sdcard_cyc, wb_sdcard_stb, wb_sdcard_we,
			wb_sdcard_addr[2-1:0],
			wb_sdcard_data, // 32 bits wide
			wb_sdcard_sel,  // 32/8 bits wide
		wb_sdcard_stall, wb_sdcard_ack, wb_sdcard_idata,
		w_sd_cs_n, o_sd_sck, w_sd_mosi, w_sd_miso, i_sd_detect,
		sdcard_int, 1'b1, sdspi_debug);

	assign	w_sd_miso = i_sd_data[0];
	assign	o_sd_data = { w_sd_cs_n, 3'b111 };
	assign	o_sd_cmd  = w_sd_mosi;
`else	// SDSPI_ACCESS
	assign	o_sd_sck   = 1'b1;
	assign	o_sd_cmd   = 1'b1;
	assign	o_sd_data  = 4'hf;

	//
	// In the case that there is no sdcard peripheral
	// responding on the wb bus
	assign	sdcard_ack   = 1'b0;
	assign	sdcard_err   = (sdcard_stb);
	assign	sdcard_stall = 0;
	assign	sdcard_data  = 0;

	assign	sdcard_int = 1'b0;	// sdcard.INT.SDCARD.WIRE
`endif	// SDSPI_ACCESS

	busexpander #(.AWIN(27), .DWIN(32),
			.DWOUT(128))
		xpandi32x128(
			i_clk, i_reset,
			wb_xpand_cyc, wb_xpand_stb, wb_xpand_we,
			wb_xpand_addr[27-1:0],
			wb_xpand_data, // 32 bits wide
			wb_xpand_sel,  // 32/8 bits wide
		wb_xpand_stall, wb_xpand_ack, wb_xpand_idata, wb_xpand_err,
			//
			rambus_xpand_cyc, rambus_xpand_stb, rambus_xpand_we,
			rambus_xpand_addr[25-1:0],
			rambus_xpand_data, // 128 bits wide
			rambus_xpand_sel,  // 128/8 bits wide
		rambus_xpand_stall,rambus_xpand_ack, rambus_xpand_idata,rambus_xpand_err);
`ifdef	SPIO_ACCESS
	//
	// Special purpose I/O driver (buttons, LEDs, and switches)
	//
	assign	w_btn = { i_btnc, i_btnd, i_btnl, i_btnr, i_btnu };

	spio #(.NBTN(5), .NLEDS(8), .NSW(8)) spioi(i_clk,
		wb_spio_cyc, wb_spio_stb, wb_spio_we,
			wb_spio_data, // 32 bits wide
			wb_spio_sel,  // 32/8 bits wide
		wb_spio_stall, wb_spio_ack, wb_spio_idata,
		i_sw, w_btn, w_led, spio_int);

	assign	o_led = w_led;

`else	// SPIO_ACCESS
	assign	w_btn = 0;
	assign	o_led = 0;
	assign	spio_int = 1'b0;	// spio.INT.SPIO.WIRE
`endif	// SPIO_ACCESS

`ifdef	PWRCOUNT_ACCESS
	initial	r_pwrcount_data = 32'h0;
	always @(posedge i_clk)
	if (r_pwrcount_data[31])
		r_pwrcount_data[30:0] <= r_pwrcount_data[30:0] + 1'b1;
	else
		r_pwrcount_data[31:0] <= r_pwrcount_data[31:0] + 1'b1;

	assign	wb_pwrcount_stall = 1'b0;
	assign	wb_pwrcount_ack   = wb_pwrcount_stb;
	assign	wb_pwrcount_idata = r_pwrcount_data;
`else	// PWRCOUNT_ACCESS
`endif	// PWRCOUNT_ACCESS

`ifdef	RTCDATE_ACCESS
	//
	// The Calendar DATE
	//
	rtcdate	rtcdatei(i_clk, rtc_ppd,
		wb_rtcdate_cyc, wb_rtcdate_stb, wb_rtcdate_we,
			wb_rtcdate_data, // 32 bits wide
			wb_rtcdate_sel,  // 32/8 bits wide
		wb_rtcdate_stall, wb_rtcdate_ack, wb_rtcdate_idata);
`else	// RTCDATE_ACCESS
`endif	// RTCDATE_ACCESS

`ifdef	BUSCONSOLE_ACCESS
	wbconsole #(.LGFLEN(6)) console(i_clk, 1'b0,
			wb_uart_cyc, wb_uart_stb, wb_uart_we,
			wb_uart_addr[2-1:0],
			wb_uart_data, // 32 bits wide
			wb_uart_sel,  // 32/8 bits wide
		wb_uart_stall, wb_uart_ack, wb_uart_idata,
			w_console_tx_stb, w_console_tx_data, w_console_busy,
			w_console_rx_stb, w_console_rx_data,
			uartrx_int, uarttx_int, uartrxf_int, uarttxf_int,
			uart_debug);
`else	// BUSCONSOLE_ACCESS

	//
	// In the case that there is no uart peripheral
	// responding on the wb bus
	assign	uart_ack   = 1'b0;
	assign	uart_err   = (uart_stb);
	assign	uart_stall = 0;
	assign	uart_data  = 0;

	assign	uarttxf_int = 1'b0;	// uart.INT.UARTTXF.WIRE
	assign	uartrxf_int = 1'b0;	// uart.INT.UARTRXF.WIRE
	assign	uarttx_int = 1'b0;	// uart.INT.UARTTX.WIRE
	assign	uartrx_int = 1'b0;	// uart.INT.UARTRX.WIRE
`endif	// BUSCONSOLE_ACCESS

`ifdef	NETCTRL_ACCESS
	// Verilator lint_off UNUSED
	wire[31:0]	mdio_debug;
	// Verilator lint_on  UNUSED
	enetctrl #(2)
		mdio(i_clk, i_reset, wb_mdio_cyc, wb_mdio_stb, wb_mdio_we,
			wb_mdio_addr[5-1:0],
			wb_mdio_data, // 32 bits wide
			wb_mdio_sel,  // 32/8 bits wide
		wb_mdio_stall, wb_mdio_ack, wb_mdio_idata,
			o_mdclk, o_mdio, i_mdio, o_mdwe, mdio_debug);
`else	// NETCTRL_ACCESS
	assign	o_mdclk = 1'b1;
	assign	o_mdio  = 1'b1;
	assign	o_mdwe  = 1'b0;

	//
	// In the case that there is no mdio peripheral
	// responding on the wb bus
	assign	mdio_ack   = 1'b0;
	assign	mdio_err   = (mdio_stb);
	assign	mdio_stall = 0;
	assign	mdio_data  = 0;

`endif	// NETCTRL_ACCESS



endmodule // main.v
