////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./board.h
// {{{
// Project:	VideoZip, a ZipCPU SoC supporting video functionality
//
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga -d -o . allclocks.txt genclk.txt netclockctr.txt global.txt icape.txt crossbus.txt wbuarbiter.txt version.txt buserr.txt pwrcount.txt rtccount.txt spio.txt gpio.txt vadj33.txt rtclight.txt rtcdate.txt exconsole.txt wbuuart.txt bkram.txt flash.txt flashcfg.txt sdram.txt zipmaster.txt mdio.txt meganet.txt protocols.txt nexbus.txt sdio.txt hdmi.txt edid.txt wboledbw.txt cpuscope.txt vidscope.txt spiscope.txt mem_bkram_only.txt mem_flash_bkram.txt xdc.txt clkcounter.txt i2ccpu.txt wbrotary.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2015-2024, Gisselquist Technology, LLC
// {{{
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
// }}}
// License:	GPL, v3, as defined and found on www.gnu.org,
// {{{
//		http://www.gnu.org/licenses/gpl.html
//
////////////////////////////////////////////////////////////////////////////////
//
// }}}
#ifndef	BOARD_H
#define	BOARD_H

// And, so that we can know what is and isn't defined
// from within our main.v file, let's include:
#include <design.h>

#ifndef	UDP_DBGPORT
#define	UDP_DBGPORT	6784
#define	UDP_DATAPORT	6785
#endif


#include <stdint.h>


////////////////////////////////////////////////////////////////////////////////
//
// ZipCPU defines and macros
// {{{
#include <design.h>

#define	_HAVE_ZIPSYS
#define	PIC	_zip->z_pic

#ifdef	INCLUDE_ZIPCPU
#ifdef INCLUDE_DMA_CONTROLLER
#define	_HAVE_ZIPSYS_DMA
#endif	// INCLUDE_DMA_CONTROLLER
#ifdef INCLUDE_ACCOUNTING_COUNTERS
#define	_HAVE_ZIPSYS_PERFORMANCE_COUNTERS
#endif	// INCLUDE_ACCOUNTING_COUNTERS
#endif // INCLUDE_ZIPCPU
// }}}


	////////////////////////////////////////////////////////////////////////
	//
	// I2C CPU data structures
	// {{{
	////////////////////////////////////////////////////////////////////////
	//
	//
#ifndef	I2CCPU_H
#define	I2CCPU_H

#define	I2CC_WAITING	0x00800000	// True if waiting for synch signal
#define	I2CC_HALT	0x00400000	// Halt request
#define	I2CC_ABORT	0x00200000	// Abort
#define	I2CC_ERROR	0x00100000
#define	I2CC_HARDHALT	0x00080000
#define	I2CC_SCL	0x00000200
#define	I2CC_SDA	0x00000100
#define I2CC_STOPPED	I2CC_HARDHALT
#define I2CC_FAULT	(I2CC_ERROR | I2CC_ABORT)
#define I2CC_CLEAR	(I2CC_FAULT | I2CC_HALT)

// For the manual port
#define	I2CC_MANSCL	0x00008000
#define	I2CC_MANSDA	0x00004000
#define	I2CC_MANUAL	0x00000800
#define	I2CC_TVALID	0x00000200
#define	I2CC_TLAST	0x00000100

typedef	struct	I2CCPU_S {
	volatile unsigned	ic_control,
				ic_override,
				ic_address,
				ic_clkcount;
} I2CCPU;

#endif	// I2CCPU_H
	// }}}


#ifndef	WBSCOPE_H
#define	WBSCOPE_H

#define	WBSCOPE_NO_RESET	0x80000000u
#define	WBSCOPE_STOPPED		0x40000000u
#define	WBSCOPE_TRIGGERED	0x20000000u
#define	WBSCOPE_PRIMED		0x10000000u
#define	WBSCOPE_TRIGGER		(WBSCOPE_NO_RESET|0x08000000u)
#define	WBSCOPE_MANUAL		(WBSCOPE_TRIGGER)
#define	WBSCOPE_DISABLE		0x04000000u

typedef	struct	WBSCOPE_S {
	unsigned s_ctrl, s_data;
} WBSCOPE;
#endif


typedef	struct OLEDBW_S {
	unsigned	o_cmd, o_override, o_addr, o_clk;
} OLEDBW;



#define	SPIO_BTNC	0x01000
#define	SPIO_BTND	0x00800
#define	SPIO_BTNL	0x00400
#define	SPIO_BTNR	0x00200
#define	SPIO_BTNU	0x00100


// Offsets for the ICAPE2 interface
#define	CFG_CRC		0
#define	CFG_FAR		1
#define	CFG_FDRI	2
#define	CFG_FDRO	3
#define	CFG_CMD		4
#define	CFG_CTL0	5
#define	CFG_MASK	6
#define	CFG_STAT	7
#define	CFG_LOUT	8
#define	CFG_COR0	9
#define	CFG_MFWR	10
#define	CFG_CBC		11
#define	CFG_IDCODE	12
#define	CFG_AXSS	13
#define	CFG_COR1	14
#define	CFG_WBSTAR	16
#define	CFG_TIMER	17
#define	CFG_BOOTSTS	22
#define	CFG_CTL1	24
#define	CFG_BSPI	31


#ifndef	WBSCOPE_H
#define	WBSCOPE_H

#define	WBSCOPE_NO_RESET	0x80000000u
#define	WBSCOPE_STOPPED		0x40000000u
#define	WBSCOPE_TRIGGERED	0x20000000u
#define	WBSCOPE_PRIMED		0x10000000u
#define	WBSCOPE_TRIGGER		(WBSCOPE_NO_RESET|0x08000000u)
#define	WBSCOPE_MANUAL		(WBSCOPE_TRIGGER)
#define	WBSCOPE_DISABLE		0x04000000u

typedef	struct	WBSCOPE_S {
	unsigned s_ctrl, s_data;
} WBSCOPE;
#endif


#ifndef	WBSCOPE_H
#define	WBSCOPE_H

#define	WBSCOPE_NO_RESET	0x80000000u
#define	WBSCOPE_STOPPED		0x40000000u
#define	WBSCOPE_TRIGGERED	0x20000000u
#define	WBSCOPE_PRIMED		0x10000000u
#define	WBSCOPE_TRIGGER		(WBSCOPE_NO_RESET|0x08000000u)
#define	WBSCOPE_MANUAL		(WBSCOPE_TRIGGER)
#define	WBSCOPE_DISABLE		0x04000000u

typedef	struct	WBSCOPE_S {
	unsigned s_ctrl, s_data;
} WBSCOPE;
#endif


// Network stream/packet interface
// {{{
#ifndef	ENETSTREAM_H
#define	ENETSTREAM_H
typedef struct ENETSTREAM_S {
        unsigned        n_rxcmd, n_txcmd;
        unsigned long   n_mac;
	unsigned	n_ipaddr;
        unsigned        n_rxmiss, n_rxerr, n_rxcrc;
} ENETSTREAM;
#endif
// }}}


//
// The Ethernet MDIO interface
//
#define MDIO_BMCR	0x00
#define MDIO_BMSR	0x01
#define MDIO_PHYIDR1	0x02	// PHY ID Register #1
#define MDIO_PHYIDR2	0x03	// PHY ID Register #2
#define MDIO_ANAR	0x04	// Autonegotiation advertisement
#define MDIO_ANLPAR	0x05	// Autonegotiation link partner ability
#define MDIO_ANER	0x06	// Autonegotiation expansion
#define MDIO_ANNPTR	0x07	// Autonegotiation next page
#define MDIO_ANNPRR	0x08	// Autonegotiation link partner next page
#define MDIO_GBCR	0x09	// 1GBase-T Control
#define MDIO_GBSR	0x0a	// 1GBase-T Status
#define MDIO_MACR	0x0d	// MMD Access control
#define MDIO_MAADR	0x0e	// MMD Access register/data
#define MDIO_GBESR	0x0f
#define MDIO_PHYCR	0x10
#define MDIO_PHYSR	0x11
#define MDIO_INER	0x12
#define MDIO_INSR	0x13
#define MDIO_LDPSR	0x1b
#define MDIO_EPAGSR	0x1e
#define MDIO_PAGSEL	0x1f

#define XMDIO_PC1R	0x00
#define XMDIO_PS1R	0x01
#define XMDIO_EEECR	0x14
#define XMDIO_EEEWER	0x10
// #define XMDIO_EEEAR	0x
// #define XMDIO_EEELPAR	0x18
#define XMDIO_LACR	0x1a
#define XMDIO_LCR	0x1c
// #define XMDIO_ACCR	0x1b

typedef struct ENETMDIO_S {
	unsigned	e_v[32][32];
} ENETMDIO;



#ifndef VIDPIPE_H
#define VIDPIPE_H

typedef struct __attribute__((packed)) VIDMODE_S {
	uint16_t	m_height,     m_width;
	uint16_t	m_vporch,     m_hporch;
	uint16_t	m_vsync,      m_hsync;
	uint16_t	m_raw_height, m_raw_width;
} VIDMODE;

typedef struct __attribute__((packed)) VIDPIPE_S {
	uint32_t	v_control, v_hdmifreq, v_sifreq, v_pxfreq;
	VIDMODE		v_in, v_src;
	const char	*v_overlay;
	uint16_t	v_ovheight, v_ovmemwords;
	uint16_t	v_ovypos,  v_ovhpos;
	unsigned	v_fps;
	unsigned	v_syncword;
	uint32_t	v_unused[512-17];
	uint32_t	v_clrmap[256];
} VIDPIPE;

#endif // VIDPIPE_H


typedef struct  CONSOLE_S {
	unsigned	u_setup;
	unsigned	u_fifo;
	unsigned	u_rx, u_tx;
} CONSOLE;

#define	_uart_txbusy	((_uart->u_fifo & 0x10000)==0)
#define	_uart_txidle	((_uart->u_tx   & 0x100)  ==0)


#define	ALTPIC(A)	(1<<(A))


////////////////////////////////////////////////////////////////////////////////
//
// SDIO SD Card constants
// {{{
////////////////////////////////////////////////////////////////////////////////
//
//

// These will be defined in sdiodrv.h for the SDIO controller
struct SDIO_S;
// }}}


//
// GPIO input wires
//
#define	GPIO_HDMIRX_CEC		0x000010000
#define	GPIO_HDMITX_CEC		0x000020000
#define	GPIO_SD_DETECTED	0x000040000
#define	GPIO_HDMITX_DETECT	0x000080000
#define	GPIO_GPS_3DF		0x000100000
#define	GPIO_SYSCLK_LOCKED	0x000200000
#define	GPIO_VIDCLK_LOCKED	0x000400000
//
// GPIO output wires
//
#define	GPIO_SET(WIRE)	(((WIRE)<<16)|(WIRE))
#define	GPIO_CLR(WIRE)	 ((WIRE)<<16)
//
#define	GPIO_HDMIRX_CEC_SET	0x000010001
#define	GPIO_HDMIRX_CEC_CLR	0x000010000
#define	GPIO_HDMITX_CEC_SET	0x000020002
#define	GPIO_HDMITX_CEC_CLR	0x000020000
//
#define	GPIO_HDMITX_EN		0x000000004
#define	GPIO_HDMIRX_HPA		0x000000008
#define	GPIO_SD_RESET		0x000000010
#define	GPIO_OLED_RESET		0x000000020
#define	GPIO_OLED_PANELEN	0x000000040
#define	GPIO_OLED_LOGICEN	0x000000080
#define	GPIO_TRACE		0x000000100
#define	GPIO_TESTHALT		0x000000200
//
#define	GPIO_EDID_SCL_SET	GPIO_SET(GPIO_EDID_SCL)
#define	GPIO_EDID_SCL_CLR	GPIO_CLR(GPIO_EDID_SCL)
#define	GPIO_EDID_SDA_SET	GPIO_SET(GPIO_EDID_SDA)
#define	GPIO_EDID_SDA_CLR	GPIO_CLR(GPIO_EDID_SDA)
#define	GPIO_HDMIRX_HPA_SET	GPIO_SET(GPIO_HDMIRX_HPA)
#define	GPIO_HDMIRX_HPA_CLR	GPIO_CLR(GPIO_HDMIRX_HPA)
#define	GPIO_SD_RESET_SET	GPIO_SET(GPIO_SD_RESET)
#define	GPIO_SD_RESET_CLR	GPIO_CLR(GPIO_SD_RESET)
#define	GPIO_HDMITX_EN_SET	GPIO_SET(GPIO_HDMITX_EN)
#define	GPIO_HDMITX_EN_CLR	GPIO_CLR(GPIO_HDMITX_EN)
#define	OLED_RESET		GPIO_SET(GPIO_OLED_RESET)
#define	OLED_RUN		GPIO_CLR(GPIO_OLED_RESET)
#define	OLED_PANELEN		GPIO_SET(GPIO_OLED_PANELEN)
#define	OLED_PANELDIS		GPIO_CLR(GPIO_OLED_PANELEN)
#define	OLED_LOGICEN		GPIO_SET(GPIO_OLED_LOGICEN)
#define	OLED_LOGICDIS		GPIO_CLR(GPIO_OLED_LOGICEN)
#define	GPIO_TRACE_SET		GPIO_SET(GPIO_TRACE)
#define	GPIO_TRACE_CLR		GPIO_CLR(GPIO_TRACE)
#define	GPIO_HALT_SET		GPIO_SET(GPIO_TESTHALT)
#define	GPIO_HALT_CLR		GPIO_CLR(GPIO_TESTHALT)




#define	SYSPIC(A)	(1<<(A))


typedef	struct	RTCLIGHT_S	{
	unsigned	r_clock, r_stopwatch, r_timer, r_alarm;
} RTCLIGHT;


#ifdef	I2CCPU_ACCESS
#define	_BOARD_HAS_I2CCPU
static volatile I2CCPU *const _i2c=((I2CCPU *)0x08002020);
#endif	// I2CCPU_ACCESS
#ifdef	SYSCLK
static volatile unsigned *const _sysclk = ((unsigned *)0x080020b0);
#endif	// SYSCLK
#ifdef	ZIPSCOPE_SCOPE
#define	_BOARD_HAS_ZIPSCOPE
static volatile WBSCOPE *const _zipscope = ((WBSCOPE *)0x08001000);
#endif	// ZIPSCOPE_SCOPE
#ifdef	OLEDBW_ACCESS
#define	_BOARD_HAS_OLEDBW
static volatile OLEDBW *const _oled = ((OLEDBW *)134225984);
#endif	// OLEDBW_ACCESS
#ifdef	PWRCOUNT_ACCESS
static volatile unsigned *const _pwrcount = ((unsigned *)0x0800209c);
#endif	// PWRCOUNT_ACCESS
#ifdef	RTCCOUNT_ACCESS
#define	_BOARD_HAS_RTCCOUNT
static volatile unsigned *const _rtccount = ((unsigned *)0x080020a4);
#endif	// RTCCOUNT_ACCESS
#define	_BOARD_HAS_BUSERR
static volatile unsigned *const _buserr = ((unsigned *)0x08002084);
#ifdef	SPIO_ACCESS
#define	_BOARD_HAS_SPIO
static volatile unsigned *const _spio = ((unsigned *)0x080020ac);
#endif	// SPIO_ACCESS
#ifdef	CFG_ACCESS
#define	_BOARD_HAS_ICAPETWO
static volatile unsigned *const _icape = ((unsigned *)0x08001800);
#endif	// CFG_ACCESS
#ifdef	VIDSCOPE_SCOPE
#define	_BOARD_HAS_VIDSCOPE
static volatile WBSCOPE *const _vidscope = ((WBSCOPE *)0x08000c00);
#endif	// VIDSCOPE_SCOPE
#ifdef	SPISCOPE_SCOPC
#define	_BOARD_HAS_SPISCOPE
static volatile WBSCOPE *const _spiscope = ((WBSCOPE *)0x08000800);
#endif	// SPISCOPE_SCOPC
#ifdef	MEGANET_ACCESS
#define	_BOARD_HAS_MEGANET
static volatile ENETSTREAM *const _net = ((ENETSTREAM *)0x08001c00);
#endif	// MEGANET_ACCESS
#define	_BOARD_HAS_BLDTIME
static volatile unsigned *const _buildtime = ((unsigned *)0x08002080);
#ifdef	NETCTRL_ACCESS
#define	_BOARD_HAS_NETMDIO
static volatile ENETMDIO *const _mdio = ((ENETMDIO *)0x08004000);
#endif	// NETCTRL_ACCESS
#ifdef	ROTARY_ACCESS
#define	_BOARD_HAS_ROTARY
static volatile unsigned *const _rotary = ((unsigned *)134226080);
#endif	// ROTARY_ACCESS
#ifdef	FLASH_ACCESS
#define	_BOARD_HAS_FLASH
extern int _flash[1];
#endif	// FLASH_ACCESS
#ifdef	GENCLKFB
static volatile unsigned *const _genclkfb = ((unsigned *)0x0800208c);
#endif	// GENCLKFB
#ifdef	VIDPIPE_ACCESS
#define	_BOARD_HAS_VIDPIPE
static volatile VIDPIPE *const _hdmi = ((VIDPIPE *)0x08003000);
#endif	// VIDPIPE_ACCESS
#ifdef	BUSCONSOLE_ACCESS
#define	_BOARD_HAS_BUSCONSOLE
static volatile CONSOLE *const _uart = ((CONSOLE *)0x08001400);
#endif	// BUSCONSOLE_ACCESS
#ifdef	VERSION_ACCESS
#define	_BOARD_HAS_VERSION
static volatile unsigned *const _version = ((unsigned *)0x080020b4);
#endif	// VERSION_ACCESS
#ifdef	NETTXCLK_ACCESS
static volatile unsigned *const _nettxctr = ((unsigned *)0x08002098);
#endif	// NETTXCLK_ACCESS
#ifdef	NETCLOCKCTR_ACCESS
static volatile unsigned *const _netclockctr = ((unsigned *)0x08002094);
#endif	// NETCLOCKCTR_ACCESS
#ifdef	SDIO_ACCESS
#define	_BOARD_HAS_SDIO
static volatile struct SDIO_S *const _sdio = ((struct SDIO_S *)0x00800000);
#endif	// SDIO_ACCESS
#ifdef	GPIO_ACCESS
#define	_BOARD_HAS_GPIO
static volatile unsigned *const _gpio = ((unsigned *)0x08002090);
#endif	// GPIO_ACCESS
#ifdef	EDID_ACCESS
#define	_BOARD_HAS_EDID
static volatile I2CCPU *const _edid = ((I2CCPU *)0x08002000);
#endif	// EDID_ACCESS
#ifdef	FLASHCFG_ACCESS
#define	_BOARD_HAS_FLASHCFG
static volatile unsigned * const _flashcfg = ((unsigned *)(0x08000400));
#endif	// FLASHCFG_ACCESS
#ifdef	RTCDATE_ACCESS
#define	_BOARD_HAS_RTCDATE
static volatile unsigned *const _rtcdate = ((unsigned *)134226088);
#endif	// RTCDATE_ACCESS
#ifdef	BKRAM_ACCESS
#define	_BOARD_HAS_BKRAM
extern char	_bkram[0x00040000];
#endif	// BKRAM_ACCESS
#ifdef	SDRAM_ACCESS
#define	_BOARD_HAS_SDRAM
extern char	_sdram[0x20000000];
#endif	// SDRAM_ACCESS
static volatile char *const _edidslv = ((char *)0x08002100);
#ifdef	RTC_ACCESS
#define	_BOARD_HAS_RTC
static volatile RTCLIGHT *const _rtc = ((RTCLIGHT *)0x08002060);
#endif	// RTC_ACCESS
//
// Interrupt assignments (2 PICs)
//
// PIC: altpic
#define	ALTPIC_UIC	ALTPIC(0)
#define	ALTPIC_UOC	ALTPIC(1)
#define	ALTPIC_UPC	ALTPIC(2)
#define	ALTPIC_UTC	ALTPIC(3)
#define	ALTPIC_MIC	ALTPIC(4)
#define	ALTPIC_MOC	ALTPIC(5)
#define	ALTPIC_MPC	ALTPIC(6)
#define	ALTPIC_MTC	ALTPIC(7)
#define	ALTPIC_CPUSCOPE	ALTPIC(8)
#define	ALTPIC_VIDSCOPE	ALTPIC(9)
#define	ALTPIC_OLEDSCOPE	ALTPIC(10)
#define	ALTPIC_UARTTX	ALTPIC(11)
#define	ALTPIC_UARTRX	ALTPIC(12)
#define	ALTPIC_RTC	ALTPIC(13)
// PIC: syspic
#define	SYSPIC_DMAC	SYSPIC(0)
#define	SYSPIC_JIFFIES	SYSPIC(1)
#define	SYSPIC_TMC	SYSPIC(2)
#define	SYSPIC_TMB	SYSPIC(3)
#define	SYSPIC_TMA	SYSPIC(4)
#define	SYSPIC_ALT	SYSPIC(5)
#define	SYSPIC_I2C	SYSPIC(6)
#define	SYSPIC_OLED	SYSPIC(7)
#define	SYSPIC_SPIO	SYSPIC(8)
#define	SYSPIC_VIDFRAME	SYSPIC(9)
#define	SYSPIC_UARTRXF	SYSPIC(10)
#define	SYSPIC_UARTTXF	SYSPIC(11)
#define	SYSPIC_SDCARD	SYSPIC(12)
#define	SYSPIC_GPIO	SYSPIC(13)
#define	SYSPIC_EDID	SYSPIC(14)
#endif	// BOARD_H
