////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./regdefs.h
// {{{
// Project:	VideoZip, a ZipCPU SoC supporting video functionality
//
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga -d -o . allclocks.txt genclk.txt netclockctr.txt global.txt icape.txt crossbus.txt version.txt buserr.txt pwrcount.txt rtccount.txt spio.txt gpio.txt vadj33.txt rtcgps.txt rtcdate.txt exconsole.txt wbuuart.txt bkram.txt flash.txt flashcfg.txt sdram.txt zipmaster.txt mdio.txt meganet.txt protocols.txt gps.txt sdio.txt cpuscope.txt mem_bkram_only.txt mem_flash_bkram.txt xdc.txt clkcounter.txt i2ccpu.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2015-2024, Gisselquist Technology, LLC
// {{{
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
// }}}
// License:	GPL, v3, as defined and found on www.gnu.org,
// {{{
//		http://www.gnu.org/licenses/gpl.html
//
////////////////////////////////////////////////////////////////////////////////
//
// }}}
#ifndef	REGDEFS_H
#define	REGDEFS_H


//
// The @REGDEFS.H.INCLUDE tag
//
// @REGDEFS.H.INCLUDE for masters
// @REGDEFS.H.INCLUDE for peripherals
#ifndef	FPGAPORT
#define	FPGAPORT	8543
#define	UARTDBGPORT	8543
#define	UARTPORT	8544
#define	UDP_DBGPORT	8545
#define	UDP_DATAPORT	8546
#endif
// And finally any master REGDEFS.H.INCLUDE tags
// End of definitions from REGDEFS.H.INCLUDE


//
// Register address definitions, from @REGS.#d
//
// ZipCPU control/debug registers
#define	R_ZIPCTRL  	0x00000000	// 00000000, wbregs names: CPU, ZIPCTRL
#define	R_ZIPREGS  	0x00000080	// 00000000, wbregs names: ZIPREGS
#define	R_ZIPS0    	0x00000080	// 00000000, wbregs names: SR0
#define	R_ZIPS1    	0x00000084	// 00000000, wbregs names: SR1
#define	R_ZIPS2    	0x00000088	// 00000000, wbregs names: SR2
#define	R_ZIPS3    	0x0000008c	// 00000000, wbregs names: SR3
#define	R_ZIPS4    	0x00000090	// 00000000, wbregs names: SR4
#define	R_ZIPS5    	0x00000094	// 00000000, wbregs names: SR5
#define	R_ZIPS6    	0x00000098	// 00000000, wbregs names: SR6
#define	R_ZIPS7    	0x0000009c	// 00000000, wbregs names: SR7
#define	R_ZIPS8    	0x000000a0	// 00000000, wbregs names: SR8
#define	R_ZIPS9    	0x000000a4	// 00000000, wbregs names: SR9
#define	R_ZIPS10   	0x000000a8	// 00000000, wbregs names: SR10
#define	R_ZIPS11   	0x000000ac	// 00000000, wbregs names: SR11
#define	R_ZIPS12   	0x000000b0	// 00000000, wbregs names: SR12
#define	R_ZIPSSP   	0x000000b4	// 00000000, wbregs names: SSP, SR13
#define	R_ZIPCC    	0x000000b8	// 00000000, wbregs names: ZIPCC, CC, SCC, SR14
#define	R_ZIPPC    	0x000000bc	// 00000000, wbregs names: ZIPPC, PC, SPC, SR15
#define	R_ZIPUSER  	0x000000c0	// 00000000, wbregs names: ZIPUSER
#define	R_ZIPU0    	0x000000c0	// 00000000, wbregs names: UR0
#define	R_ZIPU1    	0x000000c4	// 00000000, wbregs names: UR1
#define	R_ZIPU2    	0x000000c8	// 00000000, wbregs names: UR2
#define	R_ZIPU3    	0x000000cc	// 00000000, wbregs names: UR3
#define	R_ZIPU4    	0x000000d0	// 00000000, wbregs names: UR4
#define	R_ZIPU5    	0x000000d4	// 00000000, wbregs names: UR5
#define	R_ZIPU6    	0x000000d8	// 00000000, wbregs names: UR6
#define	R_ZIPU7    	0x000000dc	// 00000000, wbregs names: UR7
#define	R_ZIPU8    	0x000000e0	// 00000000, wbregs names: UR8
#define	R_ZIPU9    	0x000000e4	// 00000000, wbregs names: UR9
#define	R_ZIPU10   	0x000000e8	// 00000000, wbregs names: SR10
#define	R_ZIPU11   	0x000000ec	// 00000000, wbregs names: SR11
#define	R_ZIPU12   	0x000000f0	// 00000000, wbregs names: SR12
#define	R_ZIPUSP   	0x000000f4	// 00000000, wbregs names: USP, UR13
#define	R_ZIPUCC   	0x000000f8	// 00000000, wbregs names: ZIPUCC, UCC
#define	R_ZIPUPC   	0x000000fc	// 00000000, wbregs names: ZIPUPC, UPC
#define	R_ZIPSYSTEM	0x00000100	// 00000000, wbregs names: ZIPSYSTEM, ZIPSYS


//
// The @REGDEFS.H.DEFNS tag
//
// @REGDEFS.H.DEFNS for masters
#define	CLKFREQHZ	100000000
#define	BAUDRATE	1000000
// @REGDEFS.H.DEFNS for peripherals
#define	FLASHBASE	@$[0x%08x](REGBASE)
#define	FLASHLEN	0x01000000
#define	FLASHLGLEN	24
//
#define	FLASH_RDDELAY	1
#define	FLASH_NDUMMY	6
//
#define	BKRAMBASE	@$[0x%08x](REGBASE)
#define	BKRAMLEN	0x00040000
#define	SDRAMBASE	@$[0x%08x](REGBASE)
#define	SDRAMLEN	0x20000000
// @REGDEFS.H.DEFNS at the top level
// End of definitions from REGDEFS.H.DEFNS
//
// The @REGDEFS.H.INSERT tag
//
// @REGDEFS.H.INSERT for masters
// @REGDEFS.H.INSERT for peripherals
// Flash control constants
#define	QSPI_FLASH	// This core and hardware support a Quad SPI flash
#define	SZPAGEB		256
#define	PGLENB		256
#define	SZPAGEW		64
#define	PGLENW		64
#define	NPAGES		256
#define	SECTORSZB	(NPAGES * SZPAGEB)	// In bytes, not words!!
#define	SECTORSZW	(NPAGES * SZPAGEW)	// In words
#define	NSECTORS	64
#define	SECTOROF(A)	((A) & (-1<<16))
#define	SUBSECTOROF(A)	((A) & (-1<<12))
#define	PAGEOF(A)	((A) & (-1<<8))

////////////////////////////////////////////////////////////////////////////////
//
// ZipCPU register definitions
// {{{

#define	CPU_GO		0x0000
#define	CPU_HALT	0x0001
#define	CPU_STALL	0x0002
#define	CPU_STEP	0x0004
#define	CPU_RESET	0x0008
#define	CPU_CLRCACHE	0x0010
// (Reserved)		0x00e0
#define	CPU_SLEEPING	0x0100
#define	CPU_GIE		0x0200
#define	CPU_INT		0x0400
#define	CPU_BREAK	0x0800
#define	CPU_EXINT	0xfffff000
//
#define	CPU_sR0		0x0020
#define	CPU_sSP		0x002d
#define	CPU_sCC		0x002e
#define	CPU_sPC		0x002f
#define	CPU_uR0		0x0030
#define	CPU_uSP		0x003d
#define	CPU_uCC		0x003e
#define	CPU_uPC		0x003f

#ifdef	BKROM_ACCESS
#define	RESET_ADDRESS	@$[0x%08x](bkrom.REGBASE)
#else
#ifdef	FLASH_ACCESS
#define	RESET_ADDRESS	@$[0x%08x](RESET_ADDRESS)
#else
#define	RESET_ADDRESS	@$[0x%08x](bkram.REGBASE)
#endif	// FLASH_ACCESS
#endif	// BKROM_ACCESS
// }}}
// @REGDEFS.H.INSERT from the top level
typedef	struct {
	unsigned	m_addr;
	const char	*m_name;
} REGNAME;

extern	const	REGNAME	*bregs;
extern	const	int	NREGS;
// #define	NREGS	(sizeof(bregs)/sizeof(bregs[0]))

extern	unsigned	addrdecode(const char *v);
extern	const	char *addrname(const unsigned v);
// End of definitions from REGDEFS.H.INSERT


#endif	// REGDEFS_H
